### ISSUE TITLE
How can tests holding multiple objects be fixed?

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#1]
Test statements with more than one object being held no longer compiler.

> Test gel-bug with "tutorial off / show arm to girl / use gel on lock / put gel on lock / gel lock / apply gel to lock / use tube on lock / put tube on lock / apply tube to lock" holding the tube and the arm in the Dormitory.

Does anyone know how to fix them?

**Comment by andrewschultz** [comment]
Shooting from the hip here (fixing my own bugs) but can you do

```
to determine whether gel-bug-repro:
  if player has tube and player has arm and player is in dormitory, decide yes;
  decide no;

test gel-bug with "" when gel-bug-repro is true.

```
Or just have PURLOIN and GOTO commands? I think those would work, but there's a strong possibility I'm just Missing Something.

**Comment by curiousdannii** [comment]
The purloin idea will probably work. But I'll leave this open to see if anyone else knows.

**Comment by angstsmurf** [comment]
The problem with purloin is that it is very slow in this game and often gets stuck in disambiguation.

In my branch there is now an Ultratest action that reads from a table listing the broken tests, and moves the right objects to the player and the player to the right location before calling the standard test function. Just UTEST [test name]. If you supply the name of a test not in the table, it will fall through to the standard test function.

**Comment by angstsmurf** [comment]
Can this be considered fixed? At least the tests work now. 

I've reported this as a bug to the [Inform Mantis](http://inform7.com/mantis/view.php?id=1919).

**Comment by curiousdannii** [comment]
How did you fix it? Did you end up changing all of the affected tests to utest?

**Comment by angstsmurf** [comment]
Yes, and hijacking the "Test" command.
