### ISSUE TITLE
"examine" without arguments examines R-remover.

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#100]
Start the game, then enter "x", it will output R-remover description. I think it shouldn't silently assume R-remover, and should ask something similar to "What would you like to examine?" instead, or just output an error.

**Comment by angstsmurf** [comment]
Yeah, there are no other non-scenery objects in the starting location, so the parser assumes that the player means the letter-remover. And this game removes any messages that "clarify the parser's choice of something," such as "(the R-remover)" in this case. I'll see what can be done about this.

**Comment by angstsmurf** [comment]
1733aa4 takes care of the immediate problem, even if similar things are likely to occur in other locations and situations. Also made the response to just typing "take" slightly less confusing.

**Comment by angstsmurf** [comment]
I guess we can close this, unless anyone has anything to add.
