### ISSUE TITLE
"Matthew Rosehip" when talking with Brown

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#102]
When you first talk to Prof. Emmett Brown, amonst other things Alexandra says "There's a guy who I think is a graduate student here — Matthew Rosehip? Do you know him?".

I believe they are talking about Alex Rosehip. Should she really say "Matthew"? Was this Emily's intention to actually change the name, as if Alexandra doesn't know Alex very well and guesses his name (but then why doesn't Brown correct her), or was Alex named Matthew in early versions of script, and this is a typo?

**Comment by angstsmurf** [comment]
I guess this is something only @emshortif could answer.

**Comment by emshortif** [comment]
> On Nov 25, 2017, at 9:24 AM, angstsmurf <notifications@github.com> wrote:
> 
> I guess this is something only @emshortif could answer.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Should be Alex, yeah.
