### ISSUE TITLE
"Run-time problem P31" when playing with the "The Problem of Adjectives"

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#104]
When you first get to the Language Studies Seminar Room, you're supposed to put the book on the shelf, and then Higgate hears the conversation in Lojban coming from the hall and leaves to investigate.

You can take the book back from the shelf, though, and returning it to the shelf will replay the scene with Higgate even if she's presumably no longer here.

Even worse, if you have left the room and returned to it after this scene, and take the book from the shelf, and then return it back, not only it will replay the scene like if Higgate is in the room, but also an error will be shown:

    "Excuse me," Higgate says. "I'd better go see to that."
 
 
    *** Run-time problem P31: Attempt to use a property of 
    the 'nothing' non-object: property planned 
    conversation

This has been originally discovered on Release 6. I can at least confirm that Release 7 (Serial number 171125 / Inform 7 build 6M62 (I6/v6.33 lib 6/12N) SD // Identification number: //7B5A779B-4653-43DB-A516-F475DDC12987//) suffers from phantom Higgate reacting to the book, but because I've teleported in the Higgate's office with purloined book, I couldn't yet confirm whether "Run-time" problem still reproduces.

**Comment by toriningen** [comment]
I can't reproduce "Run-time problem", though. Were there any commits that change how Higgate works since Release 6?

**Comment by angstsmurf** [comment]
Yes, there have been a couple. Actually, I'd say there have been commits that change how pretty much everything works since Release 6.  This particular run-time problem was fixed with c1cb61d.

3051c9f should take care of the other bug.

**Comment by toriningen** [comment]
Then, this is fixed and closed, thank you!
