### ISSUE TITLE
Weird synonym for secretary's computer

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#105]
After getting back to the game I wasn't sure whether I still have my donkey around, so I have tried to `x ass` and got a weird response:

    >x ass
    (One of many beige boxes hooked into the university's main system.
 
    The secretary's computer is currently switched off.

This also reproduces on `Release 7 / Serial number 171125`.

**Comment by angstsmurf** [comment]
That is seriously weird, especially the stray single parenthesis and the change of text style.

Disabling the swearing handling of the Smarter Parser extension (the scandalous standardize swears rule) seems to fix it (f0cb0fd). I have now idea how or why it is broken, but swearing has been handled elsewhere in the code for some time now.

**Comment by angstsmurf** [comment]
Thanks for reporting this, too.
