### ISSUE TITLE
goal reveals puzzle solution

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#112]
Playing release 7:

Shortly after buying the map at the antique store, I happened to check my goals.  It told me exactly what to do with the map legend.  That's a puzzle I really would have preferred to figure out myself.  Is this intended behavior?

My suggestion is that the description of the map should hint that it may be a message from Brock (or perhaps the game could mention this when you first acquire it).  Then the goal can simply suggest that you need to figure out the hidden meaning of the map, if any.

**Comment by angstsmurf** [comment]
Thanks a lot for reporting these! I'll have a look at them soon, if nobody else does. Please don't hesitate to report any other issues you encounter while playing!

**Comment by angstsmurf** [comment]
This particular puzzle is actually given away in another place as well: if the player tries to go to the area south of Long Street before solving it, they are told, "At a guess, we're looking for a homonym paddle so we can convert the legend. I'm pretty sure they've got one in one of the fancy bars off north Long Street."

It seems likely that the reason for this hand-holding is that players used to get stuck here in older versions. There is probably no solution that will please everybody, but I guess we could make these messages a little less explicit. Perhaps @emshortif would like to weigh in?

**Comment by dbbnrl** [comment]
Yeah, I'm sure it's impossible to get a level of difficulty that appeals to every player.  Speaking for myself, I feel like the legend/legend puzzle is brilliant and hilarious... as long as it's an actual puzzle that I have to spend some time thinking about.  To have the solution handed to me on a platter before I even realized anything was odd about the original map 'legend' robbed it of all it's punch.

If the difficulty of this puzzle was already adjusted downward because people found it too hard, it probably would be crazy to bump it back up very much.  Just in case you do decide to adjust it, here are a few ideas.  I don't really love the phrasing of either of them, but you'll get the gist:

 - Add text to the top of legend description of the form _"How odd... the legend is written in Brock's handwriting, but it doesn't shed any light on the cryptic map icons.  It appears to be a story, rather than a map key."_  This reinforces the idea that the map is a message from Brock, and calls attention to the confusion of meaning, but gives no hint about how to resolve it.
 - Add text to the bottom of the legend description of the form _"Huh!  Not the kind of legend you were expecting.  Looks like Brock has been hanging out at Fleur d'Or"_.  This is a stronger hint (stronger than I'd prefer) that gives clues to both the problem and the solution.
 - Weaker versions of the above could be made by supplying only one piece of information, like just _"Huh!  Not the kind of legend you were expecting."_, or _"Huh!  Looks like Brock has been hanging out at Fleur d'Or"_.

Obviously if you did decide to add a hint of this type to the item description, you'd want to also weaken the goal text & navigation-blocking text so as not to give it away.  I'd suggest, in both cases, something about needing to figure out the message Brock has sent us within the map.

**Comment by emshortif** [comment]
I don’t honestly remember writing this goal; I agree it does seem way too explicit to me. It’s been long enough since I did this, though, that it’s possible beta-testers did express some confusion. 

I’m inclined to dial the goal back to “find a way to understand the map” (and have some similar “we should figure out the map enough to know where we’re going” refusal for the Long Street movement.

If we want to then make this easier (a bit) from there, maybe add a text like “This would be a lot more useful if it were the other type of legend” line after you examine the legend. 

Seem sensible?

Best,
Emily

**Comment by angstsmurf** [comment]
That makes sense, and I have implemented something like it in b2f7df0. Not so sure about my decision [to tack it on the end of the message about avoiding my old neighborhood](https://github.com/i7/counterfeit-monkey/blob/b2f7df01f35fde70b643440f34191cd2521209b3/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Act%20III%20Among%20Scholars.i7x#L317-L322), though. But it seems to work as intended.

As usual, any suggestions or PRs to improve my output text is more than welcome.
