### ISSUE TITLE
Alex Rosehip achievement awarded on death

### ISSUE THREAD

**Issue by ikelly** [i7/counterfeit-monkey#119]
Prior to completing the game, I died (specifically, by removing 'h' from the bushes on the path to the beach). When the game asked if we should suppose that we didn't do that, I answered no. On the game over screen I was awarded the Alex Rosehip award for completing the game in easy mode.

**Comment by angstsmurf** [comment]
Thanks for reporting this! It is a bit surprising that nobody else noticed, but I suppose most people just choose to undo death. Should be fixed by 3b9052b.
