### ISSUE TITLE
Need no invite

### ISSUE THREAD

**Issue by MechaGregzilla** [i7/counterfeit-monkey#120]
I'm not really sure where I should mention this as I'm just playing the game and am not a really a programmer. But...I've run into a situation where I can get past the guard in the antechamber of the Bureau without having the Invitation. Basically, when you have all the items in their proper state (i.e. Wig and Pass origin pasted, monocle in closed pack, etc.) , you can move to the hallway after failing the attempt once.

I'm using Gargoyle (though may not be up-to-date, if that's possible). 

If there is a more appropriate place to direct this please send me that way. thank you.

**Comment by angstsmurf** [comment]
This is the right place. Thanks a lot for reporting this! I'll take a look at it soon.

**Comment by angstsmurf** [comment]
Oh, this sounds a lot like the afterlife bug that occurred in release 5 of the game. Basically, answering yes to the question "That is, that's what would have happened if we had done something so foolish. Shall we suppose we didn't?" when losing would sometimes break the game in various ways, in particular when trying to get past the secretary in the antechamber.

Are you playing release 5? You can check this by typing VERSION.

**Comment by MechaGregzilla** [comment]
Yes, Release 5 with the secretary in the antechamber.

**Comment by angstsmurf** [comment]
Then I'm afraid you'll either have to go back to an earlier save and answer NO to cheating death when you lose, or start from the beginning with a later version.

See also #3, #5 and #45.

I'm closing this issue as a duplicate.
