### ISSUE TITLE
Lost fuel

### ISSUE THREAD

**Issue by radnor** [i7/counterfeit-monkey#129]
I poured fuel into the car and then turned it back into chard after discovering the car requires maintenance.

After discovering the mechanic, I recreate the car and have it fixed, only to discover I no longer have any way to create fuel as the funnel no longer exists.

Is it possible to create more fuel if I've already used the funnel to fuel the car?

**Comment by angstsmurf** [comment]
This is not supposed to happen! When you "uncreate" one with fuel in and then create a new one, the same fuelled one should return. I made two commits that were supposed to take care this, cdd230c and ce1c745, but apparently I did not test them enough, as I can reproduce your bug with the current code.

I'll look into it, but meanwhile it should be possible to find something else on the beach that could help you. Let me know if you need a more hints.
