### ISSUE TITLE
Put item in pack shortcut issue

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#132]
very minor:

If a gettable item is in the room and you go straight to PUT THINGY IN BACKPACK, it'll stash the item straight in the backpack--but only if the backpack is open. If you have an item in your inventory and put it in the backpack, you'll open the backpack first to put it in. It'd be a nice little convenience if the first variation on the shortcut opened the backpack just like the second.

**Comment by angstsmurf** [comment]
Thanks for reporting this as well! Should be fixed now.
