### ISSUE TITLE
Car ignition oddity

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#133]
very minor:

If you START CAR without first getting in the car or opening the car door, you'll get narration about starting the ignition (or attempting to, if you haven't fully completed the car puzzle yet). You can do this without first opening the car door or getting in the car, which is fine as a shortcut, but if you _later_ open the car door or get in, you'll get a little quip about the fact that the door is not locked--as if you'd never opened the door before. Should we first try opening the door to get at the ignition?

**Comment by angstsmurf** [comment]
Thanks for reporting these! I'll have a look soon.

You'd think that being able to skip actions like this would break puzzles and cause all kinds of trouble.

**Comment by SabreCat** [comment]
No problem! It always tickles me that this gem of a game is still maintained and updated. I ran across these things while showcasing _Counterfeit Monkey_ on a Twitch stream earlier this week. Only a few people tuned in, but at least I got to broadcast my appreciation for a while!

**Comment by angstsmurf** [comment]
An amusing detail is that before this fix, the game would automatically close the car door first if you tried to start the car while standing outside it. A nice counterpart to an old bug where you would always open the car door before doing anything to the car, even if you were sitting in it.
