### ISSUE TITLE
Orc swords can’t be interacted with

### ISSUE THREAD

**Issue by jackk225** [i7/counterfeit-monkey#137]
I am playing release 8 on normal difficulty.
After creating the “orc swords” I am not able to interact with them in any way. Any reference to “orc swords,” “orc,” or “swords” yields the response, “I can’t see what you’re talking about.”

**Comment by angstsmurf** [comment]
Nice catch! That's because their internal name is orc-swords with a hyphen, and they have not been given any synonyms. I'll fix that. Until then, referring to them as orc-swords will work.

**Comment by jackk225** [comment]
Thanks!!

**Comment by angstsmurf** [comment]
Fixed by 437687b.
