### ISSUE TITLE
“Balcony” from Deep Street is attached to Back Alley

### ISSUE THREAD

**Issue by jackk225** [i7/counterfeit-monkey#138]
The description for the “white concrete buildings” in Deep Street references a “balcony” and “laundry,” which are both highlighted. Entering “x balcony” or “x laundry” while in Deep Street does not work. However, entering “x balcony,” “x laundry,” or “x clothes” while in the Back Alley yields their respective descriptions.
Attempting to interact with the balcony in the Back Alley yields the response, “That seems to be part of the yellow buildings.” Not sure if that’s helpful.

This seems unimportant, but one of the first commands I entered when I started the game was “x clothes,” expecting to get a description of Alexandra’s outfit.

**Comment by angstsmurf** [comment]
Another nice catch! 

The word "buildings" in "The balcony is part of the buildings" was apparently understood by the Inform 7 compiler as the yellow buildings in Back Alley, so we have to be a little more specific. 

Fixed by db3c198.
