### ISSUE TITLE
“Go to paddle” allows access to Bookstore after close

### ISSUE THREAD

**Issue by jackk225** [i7/counterfeit-monkey#140]
Typing “go to paddle” as a shortcut to the Fleur D’Or causes the game to ask if you mean “homonym paddle” or the book “Pat and Chris and the Homonym Paddle.” Selecting the latter (if you aren’t currently in Deep Street) sends you inside the Aquarium Bookstore even if Lena already locked you out.

**Comment by angstsmurf** [comment]
Thanks again! The code that was supposed to prevent the player from entering the bookstore when it is closed was seriously broken. Just typing GO TO BOOKSTORE from any other location than Deep Street will get you past the door. Fixed by 2ac6267.
