### ISSUE TITLE
Problems with "passage"

### ISSUE THREAD

**Issue by jackk225** [i7/counterfeit-monkey#141]
There are possible issues with both types of passage.

Examining the paper form of "passage" gives a description, but the monocle doesn't say whether or not it is genuine.

Gelling the entryway "passage" yields "pass" but not "age".

Finally, if you try to drink the water in the Shadow Chamber, it says "Even if the Greek inscription were liquid, it would still not be nice to drink."

**Comment by angstsmurf** [comment]
Good catch! I've pushed fixes for the first and last issue. I'll have to investigate the second (gelling) thing some more.

**Comment by angstsmurf** [comment]
It was a general problem when homonym-changing things that are synthesized from several other thing. Fixed by bc81f6f.
