### ISSUE TITLE
State error applying restoration gel to oiled car

### ISSUE THREAD

**Issue by fuzzyTew** [i7/counterfeit-monkey#144]
Hi,

I got oil from soil and put it in the car with the mechanic, but didn't have fuel yet so restored the car so as to take my chard with me.  Once I found some fuel I recreated the car and tried to drive it, but it would not run.  When asked, the mechanic asked again if I had any oil, and the game commented that he showed no sign of having the conversation before.  I made new oil out of a fossil, but when I show it to the mechanic, they say I probably don't need that now, leaving me stuck.

**Comment by angstsmurf** [comment]
Thanks for reporting this! 

I can reproduce it with release 8, but not with the latest Github code (or the test version [here](https://github.com/i7/counterfeit-monkey/releases/tag/r9b))

It seems similar to #129, and commit a1dd32b which fixed that probably took care of this as well.

**Comment by fuzzyTew** [comment]
Oh, great =)
