### ISSUE TITLE
Army not highlighted in highlighting mode

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#147]
At Heritage Corner, when you examine the diorama, the code does a clever thing where it generates a "list of things on the diorama table" and then prints them out. As a result, even with HIGHLIGHTING ON, the army and the members aren't highlighted.

<details><summary>spoiler</summary>
The army is essential in hard mode, so this makes hard mode a little harder than it needs to be.
</details>

**Comment by angstsmurf** [comment]
Thanks again. This was surprisingly hard to fix, but it seems to work properly now.
