### ISSUE TITLE
Lecture Hall doesn't make it obvious that the podium can be examined

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#148]
> **Lecture Hall (at the podium)**
> The main lecture hall used for large survey courses in language studies offered to undergraduates. I sat through courses here when I was an undergraduate myself, and have now delivered a few lectures as a teaching assistant.
>  
> A poster at the front of the room announces a conference on cultural reactions to linguistic change. It is being held in Nice the day after tomorrow, with Professor Waterstone as keynote speaker, on the topic of "homonym shame". 
>  
> The room extends south, full of hard wooden seats.

The text doesn't make it clear enough that the podium is an examinable object in this room.

<details><summary>spoiler</summary>

The page is hidden on the podium. This bug makes it unnecessarily difficult to find the page.
</details>

**Comment by angstsmurf** [comment]
With e4076b4, the word "podium" and similar is highlighted.

After all this excellent testing of yours, I'm tempted to close #136 as well.
