### ISSUE TITLE
The Equipment Archive ceiling isn't highlighted

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#150]
> **Equipment Archive**
> The ceiling is mirrored, perhaps to make it harder for anyone to sneak around without being noticed among the shelves.

I think it just needs brackets around [ceiling].

<details><summary>spoiler</summary>
The ceiling mirror is essential for the Finn Rosehip achievement. This bug makes that achievement unnecessarily difficult.
</details>

**Comment by angstsmurf** [comment]
Thanks for reporting this. This was an easy fix, as expected.
