### ISSUE TITLE
Unwinnable state in Hard Mode

### ISSUE THREAD

**Issue by thehatless** [i7/counterfeit-monkey#152]
If you transform hair into air on hard mode, you lose the game. Lack of hair prevents you from making the hairpiece, lack of adjectiveless twig prevents you from making the wig, and 'air' isn't a thing you can gel.

(If you're me, you then remember you hadn't saved in a while and save over your only save file, because you know [Counterfeit Monkey is merciful](https://emshort.blog/2012/12/31/counterfeit-monkey/).)

There are backup adjectiveless chairs in Higgate and Waterstone's offices, but those rooms are perma-locked at this stage of the game. Every other chair has an attached adjective that makes it unhairable.

So, unfortunate sequence of events, but being able to make the game unwinnable feels like a bug. Even on hard mode.

**Comment by angstsmurf** [comment]
Thanks for reporting this! I wonder what the best fix would be. I guess we could just detect the unwinnable state and end the game right away, saying something like "As we soon find out, this action has doomed us," giving the player a chance to undo destroying the hair, but that would be the only place in the game that this happens. It is also a pretty strong clue to the hairpiece puzzle.

Does anyone have a better idea? @emshortif?

**Comment by thehatless** [comment]
Ideas?

1. Make 'air' a regular object.
2. Alex refuses to create air because 'we have lots already.'
3. Put spare chairs in other rooms. Refuse to turn them to air after doing so once.
4. Give existing chairs hair-friendly air-unfriendly adjectives. (Red chair! Long chair! Spiked chair!)

**Comment by angstsmurf** [comment]
Great ideas! 

I'd say the first one is probably the one that requires the least work, so I like that one. Easier than my original idea even, as it is already kind-of implemented by mistake: if you h-remove the hair while it is on the ground in the current version, it does *not* become indistinguishable from "the other air around us" but remains as a visible object, untakeable but gellable. So we could for example just make the player drop the air.

Unfortunately, this probably means we would have to implement an AI as well.

**Comment by emshortif** [comment]
I like the adjective idea, personally, because it a) fits the existing fiction and rules; b) provides a kind of mental punchline when the player realizes that a red chair _could_ meaningfully become red hair; c) doesn't raise the conceptual issue of why/how you're carrying a unit of air around. (Is it really more work than doing the air/AI solution? I suppose one then needs to put an appropriate name on the hairpiece so that "red hairpiece" becomes available.)

**Comment by angstsmurf** [comment]
If we just make the air fluid, it will automatically be non-portable ("The air, true to its nature, leaks out onto the floor.") But then we still have the conceptual issue of how we can see a unit of air on the floor and distinguish it from the other air around it.

So let's make the chair red! Although I guess that means we will have to do something about the wire chair that Nexami is sitting on at the Outdoor Café, as "wire hair" apparently is an actual thing that fox terriers can have.

**Comment by angstsmurf** [comment]
I implemented this with 739e8b8. The chair, the hair and the hairpiece are now red in hard mode. It is still possible to create a non-red chair (and hair, and hairpiece) by synthesizing CHAR and I on the dais later in the game, but a chair is too large for the university synthesizer.

I considered making a red hairband and a red hairstick as well, but decided it didn't make sense.

The air will now disappear even if created on the ground. Also added some responses to attempts to turn the wire chair into wire hair.
