### ISSUE TITLE
Publish release 9

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#156]
I think we are ready for a new release. As far as I can tell, all questionable changes have been reverted and all known bugs fixed. Everything important should be listed in the [change log](https://github.com/i7/counterfeit-monkey/blob/master/CHANGELOG.md).

I have uploaded a test build [here](https://github.com/i7/counterfeit-monkey/releases/tag/r9b7),  playable in-browser [here](https://tass.neocities.org). 

Ping @emshortif

**Comment by dfabulich** [comment]
When I test this build in Lectrote 1.3.7, the instructions to TUTORIAL OFF don't appear.

When I test this build in Spatterlight 0.5.12b, the TUTORIAL OFF instructions appear (in light grey on white, which is not enough contrast for a11y purposes) but the map doesn't.

**Comment by dfabulich** [comment]
oh, uh, I guess somehow tutorial mode persists over restarts now…? Maybe the Lectrote bug isn't a bug; I'm able to use TUTORIAL ON to turn it back on.

**Comment by angstsmurf** [comment]
Yeah, finishing tutorial mode is saved as if it is an achievement along with the others in the monkeyac.glkdata file, and if it exists, the game won't start in tutorial mode. It means that the game will always default to tutorial mode until you have finished it, so if you always turn off the tutorial at the start, it will never get finished, and so will never be off by default. I think the game has always worked this way.

The missing map is probably just the game keeping the graphics setting off across restarts. Once you have closed the map window with GRAPHICS OFF, it stays closed until you type GRAPHICS ON. I'm not entirely sure why this happens, it is not really by design, and it probably could be fixed by always explicitly opening the graphics window again after the game restarts. But I actually quite like it this way, because if I switch the map off, it is probably because I am playing on a phone and need the extra screen estate, and it would be annoying having to switch the map off again every time I restart.

I suppose the tutorial mode should really work in the same way, staying off across restarts without having to finish it first, but that would require some work. How do you think it ought to work, ideally?

The too-light grey is more of a problem, although I think most interpreters have an option to turn off text color. There is supposed to be a light grey, used for tutorial messages, and a dark grey, used for dialogue suggestions. I tried making the light grey a little darker in da94297.

**Comment by dfabulich** [comment]
No, graphics are supposedly on in my Spatterlight game.

<img width="1188" alt="Screen Shot 2020-08-08 at 5 10 35 PM" src="https://user-images.githubusercontent.com/96150/89722094-1f355000-d99a-11ea-93f1-f9d3bf039f9d.png">

**Comment by angstsmurf** [comment]
I'm afraid I can't reproduce that. That's annoying. You are on Catalina, right? I've uploaded a [new beta](https://github.com/i7/counterfeit-monkey/releases/tag/r9b6), so it would be great if you could test with that as well. Have you tried resetting the game? (Alt+Command+R, in effect deleting the autosave files and restarting.)

**Comment by dfabulich** [comment]
b6 has a map in Spatterlight. Shrug!

**Comment by dfabulich** [comment]
While testing a private build, I discovered that Spatterlight's "Reset Game" (Alt+Command+R) does _not_ reset Counterfeit Monkey's achievements! 😱

**Comment by angstsmurf** [comment]
Yeah, I don't think any interpreter has a function to delete the external files a game writes, but now that you mention it, it would actually be useful sometimes, if not exactly trivial to implement.

**Comment by emshortif** [comment]
Looks sensible to me from the description, and the in-browser version feels impressively smooth! Very nice.

**Comment by angstsmurf** [comment]
Excellent! I've uploaded [a final test version](https://github.com/i7/counterfeit-monkey/releases/tag/r9b7), in case @dfabulich or anyone else wants to do more testing. The in-browser version should also be up to date with the latest commits.

If nobody has any objections, I think we are ready to go.

**Comment by dfabulich** [comment]
Ship it! I just did a quick runthrough on easy mode and hard mode.

**Comment by angstsmurf** [comment]
The new release is [ready](https://github.com/i7/counterfeit-monkey/releases/tag/r9).
