### ISSUE TITLE
A Handful of Issues

### ISSUE THREAD

**Issue by OtherOlly** [i7/counterfeit-monkey#157]
I just played through Counterfeit Monkey, and I kept track of some of the issues I found.  I discovered after I finished that I was using Release 6 rather than the current Release 8, so I can't be certain that all of these issues are still outstanding.  I am only sharing those that I could not turn up in a search of the change log, however.  I hope the report will be of some use.

1) In Bureau Basement Secret Section.
I looked at rock-Brock with the monocle but did not apply gel to him, then I carried him out of the Sensitive Equipment Testing Room.  This triggerd the event with Alex's father, except that he wasn't able to push me into Cold Storage because the game was still treating me as looking for Brock.  When this bug is in play, I can escape through the Rotunda at any time, though there is no way to continue the story once I get outside. I can also proceed along the intended route of the game, but without ever visiting Cold Storage.

> He gives us a hard shove. We're half inside the room when we hear his last 
> remark:
> 
> "Alex... don't try to escape back through the Rotunda. If you really can't 
> come home, then head north. I've never seen it, but supposedly there's an 
> emergency exit up there."
> 
> Then he's gone.
> 
> Best to start looking for Brock where we know he went: the equipment 
> testing room.

2) In Wonderland.
After the door is created from the odor, the game behaves as if it is not there until it is opened.

> \> shoot odor
> (with the anagramming gun)
> The gun fires ruggedly into the odor, which shatters and then reforms as the
> door. It is part of the north wall, and currently closed.
> 
> [Your score has gone up by one point and is now eighty-three.]
> 
> \> n
> None of the doors in that direction look useful to us, and some of them look
> frightening.
> 
> You can go south to Bureau Basement Secret Section and east to Equipment 
> Archive from here.
> 
> \> open door
> You open the door, revealing a room beyond.
> 
> \> n
> 
> Oracle Project
> This is nothing less than the command center for a massive propaganda campaign.

3) In Tall Street.
The exit list contains a redundancy.

> The street runs west to Roundabout towards the busy roundabout.

4) In Language Studies Seminar Room.
The description of one book is probably missing the word "one."

> History of the Standards Revolution is of those bog-standard texts that everyone in my field owns a copy of and uses as a doorstop.

5) In Sigil Street.
"Window" should be plural in the seen-again description.  (I verified that this is still an issue in Version 8.)

> The reflective window of the closed shops reflect our synthesized self.

6) In the Lecture Hall (at the podium)
The description contained an error message.  (Surely this must be a rare issue or else it would have been fixed by Version 6.  I tried not carrying anything into the room, but apparently my inventory was not the problem.  I also checked back at a couple of different points in the game, but the error was always present.)

> The room extends south, full of hard wooden seats. 
> [** Programming error: tried to read (something) **]

**Comment by OtherOlly** [comment]
P. S. I may have time in a few days to replay the game using Version 8.  If I do, I will check whether these issues are still present.

**Comment by angstsmurf** [comment]
Thanks! I'll check all of these, but at least 1 and 6 should be fixed already.

If you do replay it, it would be great if you could test the current debug version [here](https://github.com/i7/counterfeit-monkey/releases/tag/r9b3) rather than release 8.

**Comment by angstsmurf** [comment]
Update: The ones that were not already fixed should be now. 

Your issue 2 is taken care of by 94af56a, 4 by 4670a30 and 5 by 0697821. I've updated [the test build](https://github.com/i7/counterfeit-monkey/releases/tag/r9b4) with these fixes.

Thanks again for reporting these.
