### ISSUE TITLE
Spill not highlighted initially

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#159]
In `Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act II Among Smugglers.i7x`

> say "Nexami nods to us. 'Watch out. That table next to you has something sticky spilled on it.' And indeed there is a spill. You were about to lean on it nonchalantly." instead.

I think this just needs brackets around `[spill]`.

**Comment by angstsmurf** [comment]
Thanks!
