### ISSUE TITLE
Can't interact with "red hair" in hard mode

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#160]
>&gt;wave c-remover at red chair
>We reset the device to c. There is a flash of red light, and the **red chair** turns into a **red hair**. A single strand, about a foot long, of red hair.
> 
>&gt;get red hair
>(I only understood the first part of that — trying anyway. Retrying that as "get red".)
> 
>Maybe that means something different to you, but I can't see any such thing.
> 
>&gt;x red hair
>(I only understood the first part of that — trying anyway. Retrying that as "x red".)
> 
>I can't see what you're talking about.
> 
>&gt;x hair
>A single strand, about a foot long, of red hair.
> 
>&gt;get hair
>We take the **red hair**.

**Comment by dfabulich** [comment]
This isn't a blocker, because you can just refer to it as "hair," but it's not great.

**Comment by angstsmurf** [comment]
Fixed by e25cb88.
