### ISSUE TITLE
toxi waste sign is now bracketed as a [bright yellow sign]

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#166]
apropos 5f0f178707b00b6bec1be8cc7950af2b59c56e5e

It's supposed to be just a `[sign]` not a `[bright yellow sign]`… the player can remove g from it to make a sin.

**Comment by angstsmurf** [comment]
Unless I'm missing something, this works as expected. The thing in brackets will be shown by its *printed name* property, which in the case of the bright yellow sign is actually just "sign".  This can be tested in a debug build with >HILIGHT, >TEST ACTIVIST. That is also why the code becomes more complex when you want something other than the printed name, such as the fossil when it is still an "odd spiral-shaped rock." 

The online build at [tass.neocities.org ](https://tass.neocities.org) has been updated, but it might be faster to just compile your own.

**Comment by dfabulich** [comment]
You're right!
