### ISSUE TITLE
Initial goals are mysterious

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#172]
I have a minor concern that may be hard to explain.  Briefly, I'm looking for situations in the game where the game seems to assume that the user knows something, but the information in question hasn't been properly introduced.

As a specific example, imagine that as a new player you read the help and learn about the 'goals' command.  If you type that command on your very first turn in Back Alley, you'll get:

> Here's what we think we need to do: 
>   Get my backpack from the cinema
>   Retrieve your remaining possessions from locker at hostel
>   Meet your colleague Slango at Counterfeit Monkey

When I saw this as a new player, my reaction was "Huh?  I guess it'll make sense later."  (Also, the inconsistent use of "my" vs "your" is odd, but perhaps some goals originate from Alex and some from Andra?  I'm unclear on this.)

I don't think this is a big deal, but it would be nice if goals don't appear until it is reasonable for the *player* to formulate them.  At this point I (the player) have no knowledge of the existence of a backpack, other possessions, somebody named Slango, or the existence of a place called Counterfeit Monkey.

There are a number of ways this could be resolved.  A few ideas:

- Have Alex mention one or more of these goals during the initial dialog.
- Have the game simply say "You need to do blah blah blah..." during the initial sequence in order to set the stage.  This feels awkward.
- Add some flavor to one of the early memories that allows you to "realize" what you need to do.

**Comment by angstsmurf** [comment]
Personally, I like fiction starting in medias res and thinking "Huh? I guess it'll make sense later." So to me this seems more like a feature than a bug.

Ping @emshortif.

**Comment by dbbnrl** [comment]
That's a reasonable perspective, and it's helped me crystallize my own thoughts.  I guess what I'm reacting to is not so much that the goals come out of nowhere, but the fact that you don't know about them *unless* you happen to type 'goals'.  My feeling is that 'goals' should summarize information that has already been presented to the player (even if that information springs unexplained from the thoughts of the PCs).  The more I think about it, the more I'm convinced that a simple opening statement (without explanation) of the starting goals would resolve my concern.

On the other hand, as I mentioned I don't think this is a very important issue and I can totally see how it could be a valid artistic decision to leave it as-is.

**Comment by emshortif** [comment]
If one wanted to change this, here is how I would do it:

- put "get back to the park" or "get out of these back streets" (or something similar) as the opening goal of the game
- do not explicitly tell the player that this is their first goal; there's enough tutorialisation going on as it is. But if they did type GOALS and saw this, I think it would be fairly comprehensible
- introduce the other goals once we're past the code-lock, at which point those other goals are more explicitly hinted in the text anyway, I believe

**Comment by angstsmurf** [comment]
I've implemented this suggestion in #177. Let me know what you think!

**Comment by angstsmurf** [comment]
Merged.
