### ISSUE TITLE
Roget Close should highlight sculpture

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#179]
Turn `highlighting on` and navigate to Roget Close.

> **Roget Close**
> A pleasantly sheltered lane in which I learned to ride a bicycle, and where my friend Lucy used to live, before she and her parents moved off-island. Restrictions were looser even twenty years ago. Our old **schoolhouse** is just west of here.
> 
> If you look just north between the houses, you'll notice also the footpath down to an almost-private beach. It used to be open, but it's now gated off, and built into the **gate** is a chic modern sculpture. 

The "sculpture" should be highlighted.

**Comment by angstsmurf** [comment]
Thanks for reporting this! Fixed in https://github.com/i7/counterfeit-monkey/commit/b566ecf9304b5c96df65199e417d9e476b63a411.

**Comment by dfabulich** [comment]
Commit https://github.com/i7/counterfeit-monkey/commit/b566ecf9304b5c96df65199e417d9e476b63a411 missed a spot when you examine the gate.

> A gate of wrought iron bars between two sturdy columns; at the moment the gate has been pushed conveniently open. Built into the right-hand column, next to the gate latch, is a curious sculpture.

**Comment by angstsmurf** [comment]
You're right. Fixed in https://github.com/i7/counterfeit-monkey/commit/d0de2a05acb576977c45442ead648caab107a58b. Thanks again!
