### ISSUE TITLE
What should happen when you put something in a container where it already is?

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#18]
One of the first changes I did when starting to work on the code was to change it so that PUT THING IN CONTAINER would no longer implicitly take the thing out of the container and then put it back in:

```
>put flash drive in backpack
(first taking the flash drive)

We put the flash drive into the backpack.

>put flash drive in backpack
(first taking the flash drive)

We put the flash drive into the backpack.
```

It seemed like an obvious bug fix, but apparently it broke the hard mode test command, which relies on you being able to put the ale into the T-inserter (turning it into a tale, putting gel on it to turn it back into an apple, p-removing it back into ale) and then to put it there again without taking it out first.

That test is easy enough to change, but I think it is actually pretty nice to be able to repeatedly t-insert things using one command rather than two ("put ale in t-inserter" instead of "take ale, put ale in t-inserter"), or changing a tale into another tale with four commands rather than six.

On the other hand, all that implicitly taking things out and putting them back in again is rather ugly and buggy. So which one is the preferred solution?

a) Leave it as it was before: inserting things into where they already are will take them out and then immediately put them back in again.

b) Leave it as it is now: you will have to explicitly take things out before putting them back in again.

c) Like a), but only with things in the T-inserter.

d) Automatically take things out of the T-inserter right after inserting (and T-inserting) them.

e) Implement some kind of activation command for the T-inserter: "ACTIVATE INSERTER" or "PUSH BUTTON" to keep inserting Ts into things without having to take them out and put them back in.

**Comment by curiousdannii** [comment]
d makes the most sense to me I think.

**Comment by angstsmurf** [comment]
Actually there is some functionality similar to d) there already: if Brock is there in the room with you, he will sometimes remove things from the T-inserter when you try to put new things in it. But it seems a little strange that he removes and tosses away the very thing you are trying to take. Perhaps it would be enough to polish this a little.

```
>[370] put ale in t-inserter
"Here, the ale is in your way." Brock fishes the ale out of the T-inserter. He tosses it in the corner.

(first taking the ale)
There are three small pops from the machine as it turns the ale into a tattle.

```

**Comment by angstsmurf** [comment]
For now I have implemented "[We] momentarily lift [the item] out of [the t-inserter] and then drop [them] back in" and "[We] momentarily lift [the item] out of [the cryptolock] and then drop [them] back in". That seemed like the simplest solution.

We should leave this open until Emily has had a chance to weigh in.

**Comment by vlaviano** [comment]
This issue goes beyond Counterfeit Monkey. I noticed it in a different context back in April and filed it as http://inform7.com/mantis/view.php?id=1894.

**Comment by emshortif** [comment]
This solution sounds fine to me. (Sorry it took so long to come back on it!)

**Comment by angstsmurf** [comment]
Thank you for your feedback! I'll close this now.

Note that since I made this and #21, I have become much more careless about making changes to the game that are more like design choices than strictly bug fixes. Please let us know if you notice anything you disagree with. Unfortunately these changes are too many to list easily, but I will get back to you about this soon.
