### ISSUE TITLE
Bugged save when showing secretary the pass

### ISSUE THREAD

**Issue by morgenman** [i7/counterfeit-monkey#180]
[save5-bugged.zip](https://github.com/i7/counterfeit-monkey/files/7148183/save5-bugged.zip)
I am using the latest build and running the game in Quixe. 
I am stuck with every command saying: "I'm handling this"

**Comment by morgenman** [comment]
It looks like this should have been fixed in version 8, but is still an issue. Hopefully this can get resolved as I am very far from a save point

**Comment by angstsmurf** [comment]
Thanks for reporting this!

I'm afraid the chances are slim that anybody knows how to hack the save file in order to help you proceed, but I'll ask at the Intfiction.org forum anyway. Most likely you will have to start over from a previous save.

The best I can do is to put in some sanity checks to prevent this from happening in future releases.

**Comment by angstsmurf** [comment]
By the way, do you happen to remember if you saw the text beginning with:

"Professor Waterstone is a busy man," I say. "If you want me to tell him you wouldn't cooperate, I'm just as happy not to work on Serial Comma Day. But if DCL wants his endorsement or advice, they'll have to work within his schedule. If you are going to turn me away, however, I would like the opportunity to speak with your manager."

before getting stuck?

**Comment by morgenman** [comment]
Yes, I did read that.
________________________________

**Comment by angstsmurf** [comment]
Thanks! That narrows down the possible causes of the bug a bit.

**Comment by angstsmurf** [comment]
Try this:
[Counterfeit-Monkey-2021-09-12-03.53.glksave.zip](https://github.com/i7/counterfeit-monkey/files/7148858/Counterfeit-Monkey-2021-09-12-03.53.glksave.zip)

Just WAIT once and then EAST three times or so.

**Comment by angstsmurf** [comment]
This seems to be caused by a general Inform 7 bug with calculation time. See https://github.com/i7/inform7-bugs/issues/15. I guess this means every `time since` statement in the game has to be rewritten.

**Comment by morgenman** [comment]
Thank you!!! The save file works perfectly!
I was not expecting to get a solution so quickly!

**Comment by angstsmurf** [comment]
Thank you! Not only did I learn how to hack save files, this also uncovered a hard-to-spot general bug that can happen in lots of places in this game, and in lots of other Inform 7 games.
