### ISSUE TITLE
Logic and crash issue during Mother scene

### ISSUE THREAD

**Issue by imxtrabored** [i7/counterfeit-monkey#181]
If you are on the futon as Alex's mother talks to you, Alex's mother will pick you up and place you on the counter (when collecting Alex's books). Doing so results in some odd grammar (as she picks up "ourselves" and we are temporarily "on my mother"). Additionally, trying to go anywhere besides getting off the counter will crash the game (probably because we aren't intended to be on the counter).

Alex's mother will also carry off impossibly heavy objects on the futon in this way as well.

**Comment by angstsmurf** [comment]
Thanks for reporting this amusing bug!

Should be fixed now.

**Comment by imxtrabored** [comment]
While on this scene, if the fridge door is unopened and you wait when she asks if you are Alex's girlfriend, if you wait one turn, Alex's mother will go into the yogurt-dinner part of the conversation, then leave without finding out you're Alex's girlfriend. The conversation kind of works if you wait out every other reply except the girlfriend one (as some kids are wont to stay in guilty silence around unfamiliar adults), but I think Alex's father specifically mentions "girlfriend" later on. Though, this could be Alex's mother making a bit of a guess, I suppose.

**Comment by angstsmurf** [comment]
Could you elaborate on how you think this scene ought to work instead?

We could just change the father's wording to "friend" depending your conversation with Alex's mother.

**Comment by imxtrabored** [comment]
The entire yogurt sequence seems a bit weird if you're not Alex's girlfriend (you start talking about going out to eat together and whether Alex made reservations for the two of you). Perhaps that can only happen if you claim to be Alex's girlfriend (or the dialogue changed if you haven't?). I think it's also a bit odd that this can distract her from her initial "who are you" question that she otherwise waits for an answer to. Regardless, I think she should at least ask the rest of her questions about Alex, even if you ignore them. As she leaves, her dialogue might change slightly (she could assume out loud that you are a friend/girlfriend and/or sound mildly irritated at your silence), then tweak Father's dialogue if needed.

**Comment by angstsmurf** [comment]
Turns out it was really easy to make the game halt until we have said we're his girlfriend, so we'll go with that. I think it is an improvement, and might be what was originally intended.

**Comment by dfabulich** [comment]
This still seems broken in pre-Release 11

`s / sit on futon / ne`

> My mother picks up ourselves and The Problem of Adjectives from the futon. Mother just stands there with an arched eyebrow. Any minute now I’m going to blurt something out through sheer force of habit.
>
> \> z
> [...]
> My mother puts The Problem of Adjectives and ourselves down on the counter.

I _am_ forced to `say we’re his girlfriend` (previously mother would go away if we just `wait` enough times), but the game still crashes if we `go ne` after mother puts ourselves on the counter.
