### ISSUE TITLE
Logic issue in letter remover shortcut

### ISSUE THREAD

**Issue by imxtrabored** [i7/counterfeit-monkey#182]
If the letter remover is in the backpack and the backpack is closed and the phrasing "remove n from target" is used, then the remover will be automatically retrieved and used on the target, but will use its previous letter setting rather than automatically changing to the specified 'n'. Trying again works as normal. Using the "wave n-remover at target" shortcut works as normal.

**Comment by angstsmurf** [comment]
Thanks again! Should be fixed now.

**Comment by imxtrabored** [comment]
No problem. And thank you for maintaining this repo.
