### ISSUE TITLE
A command to show the map full screen

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#185]
The map occupies half the screen by default. That's great on wide desktop/laptop screens, but it's not ideal even in narrow windows, and the map is illegibly small on mobile.

It is at least possible to make the map go away with `GRAPHICS OFF` (though it's not easy to discover _how_ to do that, see #186), but if you do, there's no way to glance at the map.

I suggest that there should be a command, `MAP`, which shows the map full screen; when you click or tap on it, the map should go away. It would primarily be used on mobile in `GRAPHICS OFF` mode.

**Comment by angstsmurf** [comment]
I've tried implementing this [here](https://github.com/angstsmurf/counterfeit-monkey/releases/tag/test-map).

Please try it out and let me know what you think.

Is also has the command INLINE MAP to show a map in the buffer window, but at least the Mac IDE seems to have a problem with this. Possibly because the original size of the image is too large to fit.

**Comment by dfabulich** [comment]
yeah, the inline map doesn't look too great on Parchment either. https://iplayif.com/?story=https://github.com/angstsmurf/counterfeit-monkey/releases/download/test-map/CounterfeitMonkeyMapBeta.gblorb

I think the non-inline "map" is the way to go.

**Comment by angstsmurf** [comment]
The inline map looks pretty good when I click on that link. In the Mac IDE it won't show at all. The main advantage is that it can be scrolled. Perhaps I'll leave it in as an undocumented "easter egg".

The problem with the MAP map is that, depending on the window shape, it might be cut off at the top, or still too small to read. Also, if there is an interpreter out there that supports graphics but not mouse clicks (or key press events in graphics windows), then there will be way out of the map screen.
<img width="1021" alt="Skärmavbild 2021-12-13 kl  22 44 08" src="https://user-images.githubusercontent.com/5066755/145894122-6c1471bf-a10d-4596-8e2b-4f2ee1d73c26.png">

**Comment by dfabulich** [comment]
To be clear, I was referring to showing the inline map on iOS Parchment. There, the inline map can't be scrolled (the gameport is net to `overflow-x: hidden`) though you can pinch-zoom and scroll around either the inline or full-screen map.
