### ISSUE TITLE
Set "GRAPHICS OFF" by default on mobile/narrow windows

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#186]
The map occupies half the screen by default. That's great on wide desktop/laptop screens, but it's not ideal even in narrow windows, and the map is illegibly small on mobile.

It is at least possible to make the map go away with `GRAPHICS OFF`, but it's not easy to discover _how_ to do that. You have to use `HELP` and dig around in the menus to find that command; the menus themselves are particularly challenging to work with on mobile.

Instead, I wish that the game would boot up in `GRAPHICS OFF` mode on narrow screens.

I have no idea if this is possible, but, as it stands, Counterfeit Monkey is very difficult to play on mobile, and I wish something like this could be done.

**Comment by angstsmurf** [comment]
The command GRAPHICS OFF is mentioned at the end of the tutorial, but I realise that many people may skip or miss it. I'll see what I can do.

**Comment by dfabulich** [comment]
I think the thing to do here is something similar to the "startup questions" that many IF games offer ("have you played interactive fiction before?" "do you want to enable colors?") but _not_ put them at the very start of the game.

Counterfeit Monkey has a couple of really fun startup questions ("Can you hear me?" "Do you remember our name?") and I think it would be a big loss to start the game with "traditional" startup questions. ("Do you want to enable tutorial mode?" "Do you want to enable graphics?")

_But_ I think it would make sense to leave the map off by default for a few turns at the start of the game. (It's already off by default when answering the opening questions.) And then, in tutorial mode, actually stop and ask the player whether they want to enable the on-screen map, perhaps as the player leaves Ampersand Bend to enter the Fair.

> This game includes a map. Would you like to enable it?

If they say "YES," mention that you can type "GRAPHICS OFF" to turn it back off. If they say "NO," mention that they can type "GRAPHICS ON" to turn it back on, or "MAP" to see the full-screen map.

I think I'd also pose that question if/when the player types "TUTORIAL OFF."

(Or perhaps make this the very first tutorial hint? "This game includes a map. You can type `GRAPHICS ON` to show the map on the side of the screen, or just type `MAP` to show the map full screen.")

**Comment by dfabulich** [comment]
Since "GRAPHICS" and "MAP" are so interrelated, maybe combine them into a single "MAP" command?

* `MAP` to show the map full screen. (Mention that you can type `MAP ON` after dismissing the map.)
* `MAP ON` to show the map on the side pane. (After typing `MAP ON`, mention you can type `MAP OFF` to hide it.)
* `MAP OFF` to hide it. (When you `MAP OFF`, mention that you can type `MAP ON` to bring it back, or just `MAP` to show the map full screen.

**Comment by angstsmurf** [comment]
In the test version linked in the other issue, the map will only be opened automatically if the game thinks that the window is wide enough. Otherwise there will also be a new tutorial message about how to turn the map on.

**Comment by dfabulich** [comment]
Oops, I didn't read your build description. Yeah, what you've got works pretty well. (I still think it would make sense to combine `GRAPHICS` and `MAP` into a single verb.)

**Comment by angstsmurf** [comment]
Mostly implemented in 44c5ddb.
