### ISSUE TITLE
Invisible question when restarting

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#187]
Launch Counterfeit Monkey, type "yes", "andra", then type "restart".

The screen will be blank except for the cursor; you won't be able to see the question, "Can you hear me? >> "

Type "yes" and you'll see the expected question "Do you remember our name?" with a `>` prompt. Type "andra". You'll see the introductory text, "Let’s try to get a look around…" but the `>` prompt line is missing.

If you type any command at that point, the `>` prompt comes back and the game works normally.

I'm able to reproduce this on iplayif.com https://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Fi7%2Fcounterfeit-monkey%2Freleases%2Fdownload%2Fr10%2FCounterfeitMonkey-10.gblorb and in Spatterlight 0.8.9.

**Comment by angstsmurf** [comment]
This is one of those bugs that I've noticed from time to time, but which always seems to disappear when I try to debug it. See for example https://github.com/erkyrath/lectrote/issues/124. It seems to have something to do with @curiousdannii's startup precomputation code which tries to load data at start from a resource stream in the blorb or from an external file.

**Comment by dfabulich** [comment]
Just to be clear, are you able to successfully reproduce the bug? For me it reproduces 100% of the time when restarting in Spatterlight and on iplayif.com.

**Comment by angstsmurf** [comment]
Yes, I can reproduce it with CM version 10. Not if I build a new version, though. It might be because the release version has a resource stream in the blorb.

Ping @curiousdannii, do you have any idea what is going wrong here?

**Comment by curiousdannii** [comment]
If it's printing to the status window, then it must be focusing the window wrongly. Sounds like it could be https://github.com/i7/extensions/issues/70 ? Looks like it's been years since Flexible Windows was updated here.

**Comment by angstsmurf** [comment]
Thanks a lot! It sounds exactly like the bug that the new Flexible Windows is meant to fix.

To make the new version work, I had to add back some of the lines that were deleted from the old version. Hopefully that didn't cause any new problems.
