### ISSUE TITLE
Changelog doesn't mention removed objects/responses in a previous release

### ISSUE THREAD

**Issue by zyx-xyzzy** [i7/counterfeit-monkey#193]
Looking back at some previous PRs, I noticed that while #145 was implemented for Release 9, none of its changes aside from the update to creature behavior in containers are listed in that release's changelog entry. Shouldn't such a major edit be properly documented?

(As an aside while we're talking about that PR anyway, IMO removing existing game content just because you aren't fully satisfied with the description or because it makes the game larger is kind of against the spirit of a game where you're encouraged to experiment with the transformation tools to discover new words and responses... but ofc I recognize that as a random nobody coming in late I'd just be (understandably) overruled if I were to try to make an issue or PR about restoring it, so ¯\_(ツ)_/¯)

**Comment by angstsmurf** [comment]
No, nothing was removed from the previous release, except what is mentioned in the change log. #145 removes experimental stuff that was introduced after release 8, and which was never included in any official release.
