### ISSUE TITLE
Ship Release 11

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#196]
There's been quite a bit of work done in this repository since Release 10 in March 2021. (I'm particularly enthusiastic to ship mobile-friendliness enhancements.)

**Comment by angstsmurf** [comment]
Sure. What does @emshortif  think?

**Comment by emshortif** [comment]
I have no objections if the team feels it’s ready to go.

**Comment by angstsmurf** [comment]
Haven't heard a lot from the team lately. Does @i7/counterfeit-monkey  feel it’s ready to go?

**Comment by dfabulich** [comment]
If you have a pre release build, I’d be happy to run through it.

**Comment by angstsmurf** [comment]
Here you go: [Pre-release build](https://github.com/i7/counterfeit-monkey/releases/tag/r11).

**Comment by dfabulich** [comment]
I deleted my `~/Library/Containers/net.ccxvii.spatterlight/Data/Library/Application Support/Spatterlight/Gluxe Files` folder (including `monkeyac.glkdata`) and started a fresh game of Counterfeit Monkey with the pre-release build. I then played through the whole game, unlocking all achievements, with highlighting on, using exclusively the new `remove X from Y` syntax for letter removal.

I successfully saved and restored, no problem (#191) and I restarted without issue (#187)

#181 wasn't fixed.
We missed a spot in #184.

I also filed a few new issues: #195 #197 #198 #199 #200. Of those, I think only #199 really ought to be fixed before release; the others could let slide. (But I'd especially love it if #195 were implemented.)

Also, I was really hoping that this version would be highly playable on Parchment for iPhone, thanks to the fix for #186, but when I tried it, I found https://github.com/curiousdannii/parchment/issues/134 That's a real bummer, but it may not make sense to try to fix that before shipping Release 11. (It's not even clear to me whether we should treat this as a bug in Parchment or Counterfeit Monkey or what.)

**Comment by angstsmurf** [comment]
I think all the important stuff is implemented now. Another pre-release testing version: https://github.com/i7/counterfeit-monkey/releases/download/r11b/CounterfeitMonkey-11b-pre.gblorb

**Comment by dfabulich** [comment]
I did a quick run through. #181 is now fixed. #199 is not fixed… it appears unchanged.

How do you feel about #197? And while I recognize that #195 might be a lot, I also suggested a text change, which I've now filed separately as #202. Could we do #202, even if we're not doing #195??

**Comment by dfabulich** [comment]
(Might I request permissions to reopen issues on this repository?)

**Comment by angstsmurf** [comment]
You'd have to ask @curiousdannii. I don't have admin privileges here, or whatever the correct term is.

**Comment by curiousdannii** [comment]
Think I've given you permission now.
