### ISSUE TITLE
After using MAP command, commands appear double printed to the screen

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#199]
I'm playing in Spatterlight, and I reset the game with alt-Cmd-R. Then I typed `y / n / n` to get to the command prompt.

Then I typed `MAP` to see the full screen map, and pressed a key to dismiss the map.

From then on, anything I type appears echoed in the transcript after I type it. For example, in the screenshot below, I typed `look at the yellow buildings` on the command prompt next to the `>`, but the next line is just my own message echoed back to me again in green.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/96150/216205110-8e162a44-1b8d-4592-93ae-f7a21b987321.png">

**Comment by dfabulich** [comment]
Doesn't appear to be fixed in https://github.com/i7/counterfeit-monkey/releases/download/r11b/CounterfeitMonkey-11b-pre.gblorb

**Comment by angstsmurf** [comment]
Drat. I apparently only tested it in Gargoyle, where it is fixed.

**Comment by angstsmurf** [comment]
Seems I can no longer reproduce this. Some obscure, self-correcting autosave bug in Spatterlight, perhaps.

**Comment by dfabulich** [comment]
Aha! I think the repro requires turning the map off first. If the map is on, typing `map` doesn't repro the bug.

Here's what I did.

1. Quit Spatterlight
1. Delete `Glulxe Files`
1. Start 11b-pre. If you did it right, you'll see the prompt, "Can you hear me?" discarding any previous autosave.
1. Just in case, reset the game with alt-Cmd-R.
1. `y / andra / map off / map / look`

… and then `look` appears double-printed.

**Comment by angstsmurf** [comment]
Now it really should be fixed. Try this:
[CounterfeitMonkey-11g-pre.gblorb.zip](https://github.com/i7/counterfeit-monkey/files/10608579/CounterfeitMonkey-11g-pre.gblorb.zip)

**Comment by angstsmurf** [comment]
I think this can be closed. Feel free to reopen if you can still reproduce it.
