### ISSUE TITLE
Cold Storage Fast Travel Glitch

### ISSUE THREAD

**Issue by DefKonOne** [i7/counterfeit-monkey#213]
Late game spoilers warning:

The fast travel command 'go to [x place]' from the t-inserter room in the bureau executes with no issue, making it so that you are able to bypass the event with Alex's father and avoid being put into cold storage, at least for me. I assume there was supposed to be code that forces you to go through the event, as fast traveling out of the university, for example, stops you at the oval to watch Higgate's arrest sequence if you haven't yet, but either it didn't execute for me or it was missing altogether. Instead, I have to backtrack to the t-inserter room and specifically leave or walk east to get put into cold storage.

Because of this, after bypassing the event, you could go back into the bureau basement and complete the game without ever getting fused. The game treats it as though Alex is in control, forcing you to revive Atlantida, and as though you betrayed Brock in cold storage, even though Brock was still in your inventory before getting to the yacht. However, 'we' pronouns are still used for the narration throughout the ending (because of bypassing the cold storage trigger that changes pronouns) and looking at yourself does not indicate who's dominant like it normally would.

**Comment by angstsmurf** [comment]
Thanks for reporting this!

It was a pretty serious bug and surprisingly tricky to fix. Hopefully 1ffa4fe takes care of it.
