### ISSUE TITLE
Double message when not being allowed to use the remover 

### ISSUE THREAD

**Issue by eriktorbjorn** [i7/counterfeit-monkey#214]
In the Antechamber, I wanted to mess with the secretary's stool, so I tried this:

> &gt; POINT S-REMOVER AT STOOL
> Better not. We don't want the secretary to see the **Origin Paste**.
>
> I can't see what you're talking about.

At the time, my remover was an I-remover, and the game had automatically stashed it in my backpack, and then closed the backpack. Pointing the I-remover at the stool only prints the first message, so I'm guessing that the action was intercepted even before changing the settings on the remover (which seems correct). But apparently that that still didn't stop it from then trying to use the non-existing S-remover.

**Comment by eriktorbjorn** [comment]
I removed the removed from the backpack and left the backpack outside. The message I got then was a bit clearer, I guess:

> &gt; POINT S-REMOVER AT STOOL
> Better not. We don’t want the secretary to see the **I-remover**.
> 
> I can’t see what you’re talking about.

**Comment by dfabulich** [comment]
Normally when you try to adjust the remover while it's in your backpack, there's a parenthetical, "(opening the backpack)".

>\> remove s from sword
>(opening the backpack)
>We reset the device to s. The sword gives way to the now-familiar word.

Seems like that should show up here.

>\> POINT S-REMOVER AT STOOL
> (opening the backpack)
> Better not. We don't want the secretary to see the Origin Paste.

Even if it then added "I can't see what you're talking about," at least then it would be clear why.

**Comment by angstsmurf** [comment]
943b9d7 should take care of this particular case.

There are still a couple of `try opening the backpack` left where we don't handle the the failure case (such as [here](https://github.com/i7/counterfeit-monkey/blob/943b9d763e01434d91e1e114fb4c2538456824da/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Features%20of%20Created%20Objects.i7x#L49)), but it didn't seem worth the trouble figuring out how to deal with it. Hopefully the opening action won't ever fail in those cases.
