### ISSUE TITLE
Missing highlighting: the hook/pulley in Tunnel through Chalk

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#217]
> **Tunnel through Chalk**
> This passage has been cut through natural cliff rock and looks older than the Bureau itself. The walls are rough-hewn, exposing **sedimentary strata**. Here and there it looks as though someone has actually excavated a favored rock or relic.
> 
> Blocking the far end of the corridor is a metal **portcullis**. It is currently lowered. From the pulley above the portcullis hangs a **counter**. 
> 
> I can go **east** through the **portcullis** (closed) and **up** to the Surveillance Room from here.
> 
> \> **get counter**
> I pick up the **counter**. One of those devices with a press-button to increment a number, to assist with counting things like the number of people attending an event. There’s also a loop to let the user wear it over one finger. The counter currently reads 17.
> 
> A breeze along the passage stirs the dust.
> 
> \> **look**
> **Tunnel through Chalk**
> This passage has been cut through natural cliff rock and looks older than the Bureau itself. The walls are rough-hewn, exposing **sedimentary strata**. Here and there it looks as though someone has actually excavated a favored rock or relic.
> 
> Blocking the far end of the corridor is a metal **portcullis**. It is currently lowered. There’s a pulley and hook arrangement above the portcullis, but the hook is empty. 
> 
> I can go **east** through the **portcullis** (closed) and **up** to the Surveillance Room from here.
> 
> The air stirs with a breeze from the east.

The hook/pulley should be highlighted.

**Comment by angstsmurf** [comment]
Should be fixed in https://github.com/i7/counterfeit-monkey/commit/c90e61b8439f57341625d86b6c78057fe1f57191 .

>Blocking the far end of the corridor is a metal **portcullis**. It is currently lowered. From the **pulley** above the portcullis hangs a **counter**.

>Blocking the far end of the corridor is a metal **portcullis**. It is currently lowered. There's a **pulley and hook** arrangement above the portcullis, but the hook is empty.
