### ISSUE TITLE
Support common contractions

### ISSUE THREAD

**Issue by Stealthii** [i7/counterfeit-monkey#222]
Common contractions such as "what's" and "he's" aren't supported:
```
>ask man what's worth seeing
That doesn't seem to be a topic of conversation at the moment.
 
>ask man what is worth seeing
"So tell me, what should I be looking for in the New Church?" we ask.
```
```
>ask man why he's here
If you're trying to converse with other characters...

>ask man why he is here
"If you aren't interested in this place, why do you volunteer here?" we ask.
```

It would be nice if these were supported throughout the language as a known alias of their counterparts.

---

Suggestive list:
> what's -> what is
> he's -> he is
> demo -> demonstration

**Comment by angstsmurf** [comment]
Thanks for reporting this! That would certainly be nice.

Testing this also uncovered a bug in the macOS Inform IDE interpreter, which echoes apostrophes as question marks and gives a run-time error:

<img width="285" alt="Skärmavbild 2023-10-30 kl  21 39 31" src="https://github.com/i7/counterfeit-monkey/assets/5066755/049fed41-b2b4-44a5-a3db-c5d1033acec6">

**Comment by angstsmurf** [comment]
Started a forum thread about the apostrophe problem, semi-related to this issue:
https://intfiction.org/t/help-me-fix-these-counterfeit-monkey-bugs/65468/14

**Comment by angstsmurf** [comment]
They should all work now.
