### ISSUE TITLE
Run-time problem P60: when soap falls onto floor

### ISSUE THREAD

**Issue by Stealthii** [i7/counterfeit-monkey#223]
After removing the sinks, and utilising the soap dispenser, we get a P60 error when the target is no longer the Sink but the Public Convenience:
```
>wave s-remover at sinks
>take soap
We give the dispenser a squeeze and it deposits some soap on the floor, the sink having been removed from the area.
 
*** Run-time problem P60: Attempt to set a variable to the wrong kind of object: you wrote 'now target is the location', which sets the value to the Public Convenience - but that doesn't have the kind 'thing'.
 ```

**Comment by angstsmurf** [comment]
Thanks for reporting this! I obviously did not test this part of the code properly.

Fixed by https://github.com/i7/counterfeit-monkey/commit/8c4e715860fbdb4d71ce4935c965ef9e40cde4d5.
