### ISSUE TITLE
We can r-remove Brock

### ISSUE THREAD

**Issue by Roachbones** [i7/counterfeit-monkey#234]
We can't b-remove Brock into a rock without first testing the T-inserter, but we can r-remove him.

> \>b-remove brock
> We reset the device to b. Brock would never forgive us if we turned him back into a rock now.
> 
> When he thinks we're not looking, he ogles our backside. I look away again.
> 
> \>r-remove brock
> We reset the device to r. With a distinct whiff of beer, Brock turns into a bock. It's a bottle of strong German lager with a goat on the label.
> 
> \>take bock
> We take the bock.

This is somewhat game-breaking. We can leave the T-inserter early, and we can later gel the bock.

Looks like the bock was added in release 5 as a derivative of brock, but some rules seem to assume Brock can only be the roc(k):

```
Instead of putting gel on the rock when cold dilemma has ended and Sunning Deck is not visited:
	say "Having two people to smuggle back to the yacht will just make this trip twice as hard to accomplish."
```

**Comment by angstsmurf** [comment]
I would assume that simply adding a rule that prevents r-removing Brock is enough to fix this. It is already impossible for the player to ever turn Brock into a rock, so it should be equally impossible to turn him into a (bottle of) Bock. Or have I forgotten something?

**Comment by Roachbones** [comment]
I forgot that Brock does us the favor of B-removing himself, so the player never has to letter-remove him. I think you're right. Maybe just this?

```
Check waving the letter-remover at Brock when the current setting of the letter-remover is "r":
	say "Brock would never forgive [us] if [we] turned him into a bock now." instead.
```

**Comment by angstsmurf** [comment]
Thanks for this! I erroneously changed it to Bock with a capital B, but it is now fixed.
