### ISSUE TITLE
Old bug list from Emily

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#24]
This list is actually pretty interesting. Despite the name it seems plenty of these still apply, especially those at the top. Perhaps we should ask Emily about which issues are still relevant, and go through it and check them ourselves.

[counterfeit-monkey/Counterfeit Monkey.materials/bugfix list for rel 3](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/bugfix%20list%20for%20rel%203)

**Comment by andrewschultz** [comment]
Maybe you can run Zarf's regression test suite on it? I've had good luck with my own games doing so. My guess is that debug commands could be handy sweeping through them.

I'm not sure how much regression testing is already done, but it seems like these would be nice to throw on the pile.

**Comment by angstsmurf** [comment]
Most of these are probably not regressions, but things that have always been there. There are a lot of useful tests commands in there already, like TEST CRATE-BUG that demonstrates that you can leave essential things behind in the converted crate. But regression testing would be great, especially if we could automate it with Travis.

**Comment by angstsmurf** [comment]
I'll try adding as many bugs as possible from this to the issue tracker, so that we get a nice long list to tick off. If anyone wants me to stop doing this, just let me know.

**Comment by emshortif** [comment]
This is marked as needing my input, but it looks like it's under control, really.

**Comment by angstsmurf** [comment]
Yeah, I think I've found the answer to most of the questions I had back when adding the label asking for your input. The majority of the things listed should be fixed or implemented now.

**Comment by angstsmurf** [comment]
I found a file on my computer where I had deleted all the things I considered done on this list. This is what was left:

> Gelling the garage or mechanic is a really unintuitive game over,
treating the mechanic as a glitch seemed to say he was something to be
undone, not someone who has awareness to escape restoration.

>I think that I ought to get still more money in the endgame, or perhaps an achievement, for turning the oil paintings (long believed lost) into intaglio pins and smuggling them out with me.

>Add an achievement for Rite? 

>-- add hint system
>-- improve alternate dialogue for characters
>	-- make sure that alternate dialogue is successfully represented with topics

TOPICS now basically lists every viable quip, with some exceptions. It is not pretty, but at least all alternate dialogue is now possible to find.

>-- provide a full walkthrough as well 
>-- add achievements for
>	-- getting away with the oil paintings or equivalent
>-- create achievement-hint system

>horrific things to do that at least deserve a comment of some kind:
>	-- turning the museum's prize display into a cod

>CANNOT REPRO. in the hostel bedroom, using the remover on the bed will give locked
up end even if you pick a letter not in "dorm bed". same with being in
the bed when applying it.
>
>CANNOT REPRO. 2) Also, in the T-insertion machine section, when you’re still experimenting and aren’t supposed to be able to leave the room, if you turn Brock back into a rock it lets you leave, thereby prematurely triggering the meeting with your father. However, instead of then being sent to the cold storage room, you’re free to wander around, meaning that you can go back into the T-insertion machine room, complete the experimentation, and then be unable to progress since the cold storage sequence will not trigger. 

You can still bypass the T-insertion testing puzzle by turning Brock back into a rock, but it won't break the game. Actually I quite like that as an alternative solution.

>CANNOT REPRO. 20) >say we’re Alex’s girlfriend
I didn’t understand that number.

This last one sounds like a bug in Numbered Disambiguation Choices, and we have fixed many of those.

**Comment by emshortif** [comment]
I think I'd be inclined to add an exception letting the player gel the garage/mechanic, since alternatives feel more complicated.

When you say TOPICS is not pretty, is there something there where it would be useful for me to weigh in on what should be in vs. out?

**Comment by angstsmurf** [comment]
Looking at this again, I hadn't realized until now that the game over when gelling the mechanic is the effect of a [general dangerous destruction rule](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Safety%20Overrides%20and%20Disasters.i7x#L21) that prevents us from killing people by destroying the thing they are in or on. It is trivial to allow this for fake people, so let's do that.

TOPICS will now sometimes produce a list that is on the longish side. We don't list the Threaded Actions quips, location-questioning quips or vegetable recommendations, but you still get things like 

> We want to ask whether public transport exists here, ask whether we can keep the guidebook, ask whether there is an internet connection nearby, ask whether there are beds available, ask what the fair is for, ask what she recommends seeing in city, ask whether the attendant enjoys her job, or compliment the nose ring.

and

> We want to ask when the movie starts, ask what the movie is, ask whether he likes his job, ask whether crime could ever be justified, ask whether the government is just, ask whether immigration laws are fair, ask whether he has ever been in trouble with the law, ask what he likes to eat, or ask where my backpack is.

Of course, this is really only applies to the hostel attendant and the ticket collector.

**Comment by emshortif** [comment]
Yes, agreed -- that doesn't seem long enough or frequent enough to deserve much worry.

**Comment by angstsmurf** [comment]
I guess we can close this for now, unless anyone disagrees. There are still a couple of things on the list which are yet to be done, such as a hint system and hints for the achievements, but these would probably be better to add as separate issues.
