### ISSUE TITLE
Local looking taking precedence over examine

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#27]
I worked around another bug where the parser would always examine the location instead of the thing I was trying to examine. This time it was the podium in Lecture Hall 1, the last time it was the maps collection in the antiques shop.

When the name of an object is included in the name of a room, such as the podium in Lecture Hall (at the podium), the parser will always think that we mean the room and not the object when trying to examine it. 

@vlaviano [explained earlier](https://github.com/i7/counterfeit-monkey/issues/15#issuecomment-223839241) that this is because local looking grammar line for examine is placed before the regular one.

And sure enough, this is in the i6 code:
Verb 'examine' 'x//' 'watch' 'describe' 'check'
    * 'indoors'  -> A242_checking_indoors
    * scope=Scope_Filter_43  -> A123_local_looking
    * noun  -> Examine
    * 'repository' 'descriptions'  -> A243_checking_repository_des
    * noun 'with' / 'through' held  -> A197_looking_at_it_through

Something must have changed since 6G60 in the way this is handled. 

Is there any simple way to fix this? I've experimented with "Understand nothing as examining", but when I declare a new grammar line for examine, it ends up below the local looking line.

**Comment by vlaviano** [comment]
Try
```
Understand the command "check" as something new.
```

**Comment by vlaviano** [comment]
It's interesting that the local looking line appears before the regular examine line, while the looking at it through line appears after. I'm curious what would happen if you moved the definition of local looking to Tools.i7x where looking at it through is defined.

**Comment by angstsmurf** [comment]
I'm afraid that doesn't seem to have any effect. The i6 code is identical even if I move the local looking definition after the looking at it through definition.

**Comment by vlaviano** [comment]
Yeah, I figured that that would be the case after looking at the 'check' stuff and edited my message accordingly. We need to learn what controls the order of the grammar lines.

**Comment by vlaviano** [comment]
Here's a test program that demonstrates the issue:
```
Test Chamber is a room.

A test tube is a thing in Test Chamber.

Definition: a room is locally present if it is the location.

Understand "examine [any locally present room]" as local looking.

Local looking is an action applying to one thing.

Carry out local looking:
	try looking.

Test me with "x test / x test tube / x test chamber".
```

**Comment by vlaviano** [comment]
§17.22. (Precedence) sheds some light on this. It says that more specific grammar lines precede less specific ones. So the issue might be that [any locally present room] is considered to be more specific than 'noun'.

**Comment by vlaviano** [comment]
Here's one really cheesy solution:
```
Definition: a thing is thingy if it is a thing.

Understand "examine [thingy thing]" as examining.
```
When added to the test program, this produces:
```
Verb 'examine' 'x//' 'watch' 'describe' 'check'
    * noun=Noun_Filter_2  -> Examine
    * scope=Scope_Filter_1  -> A77_local_looking
    * noun  -> Examine
;
```

**Comment by angstsmurf** [comment]
I like that.

**Comment by angstsmurf** [comment]
I don't think we're likely to come up with anything better. Would you like to commit that?

**Comment by vlaviano** [comment]
I find it humorous, but I'm not really thrilled with it. Let's see what @curiousdannii thinks.

**Comment by angstsmurf** [comment]
Somewhat surprisingly, this seems to do it as well:

`Understand "examine [thing]" as examining.`

**Comment by vlaviano** [comment]
Here's some discussion on the I7 uservoice forums about allowing reordering of grammar lines: https://inform7.uservoice.com/forums/57320-general/suggestions/751440--parsing-a-way-to-order-understand-lines-explicit. It's 6 years old and has 0 votes, but at it was on the radar at one point.

**Comment by angstsmurf** [comment]
Well, now it has my vote at least.

**Comment by curiousdannii** [comment]
I'm away from home so can't test anything. Could did the player mean rules help? Would changing local looking to "examine [location]" work?

**Comment by vlaviano** [comment]
The "does the player mean" rules won't help, because the problem isn't disambiguation between objects for a single grammar line. It's one grammar line succeeding before a later one is tried. We'll try out your other suggestion.

**Comment by vlaviano** [comment]
> The only thing that remains broken is "look at". I still can't make that work as a synonym for examine. Looking at the location takes precedence again

This works with the test program:
```
Understand "look at [any locally present room]" as local looking.
Understand "look at [thing]" as examining.
```

**Comment by curiousdannii** [comment]
One more thought, should this be changed to say one room? 

    Local looking is an action applying to one thing.

**Comment by vlaviano** [comment]
> Would changing local looking to "examine [location]" work?

I think that this leads us back to the current implementation.

There's no [location] grammar token, and trying to create one leads us to [locally present room]. 

Rooms aren't typically in scope when matching tokens, and trying to change that leads us to adding "any" to our grammar token (see §17.7. Understanding any, understanding rooms). 

Finally, there's a difference between examining a room (when we rewrite the grammar to allow it) and looking. We get the room description, but we don't get the room name, the contents, the visited flag being set, etc. If we want the correct behavior, at some point the examine has to be translated to a look or something that produces an equivalent room description.

> One more thought, should this be changed to say one room?

It seems like it should, but it won't compile:

> "You wrote 'Local looking is an action applying to one room'  : but an action can only apply to things or to kinds of value, for instance: 'photographing is an action applying to one visible thing'." 

Strangely, if I replace room with object, it compiles. There's a reference [here](http://www.ifwiki.org/index.php/Inform_7_for_Programmers/Part_3) to "Teleporting to is an action applying to one room." and one [here](http://inform7.com/extensions/Ron%20Newcomb/Editable%20Stored%20Actions/doc_0.html) to "Guarding it from is an action applying to one room and one direction.", but [this thread](http://www.intfiction.org/forum/viewtopic.php?t=7383&p=49968) suggests that it doesn't work. Maybe it's deprecated, or a bug.

**Comment by vlaviano** [comment]
What does the 'look' grammar look like in the generated I6 code?

**Comment by angstsmurf** [comment]
The line for "look at [thing]", (* 'at' noun=Noun_Filter_25  -> Examine), is before the line for "look at [any locally present room]", (* 'at' scope=Scope_Filter_26  -> A123_local_looking). But the line " * scope=Scope_Filter_27  -> A123_local_looking" wins, because it matches "at podium" with a room.

```
Verb 'look' 'l//'
    *  -> Look
    * 'carefully'  -> A81_bold_looking
    * 'closely'  -> A81_bold_looking
    * 'around'  -> Look
    * noun=Noun_Filter_24  -> Examine
    * noun=Noun_Filter_28  -> A124_facing
    * scope=Scope_Filter_27  -> A123_local_looking
    * noun  -> Examine
    * Cond_Token_1381 Mistake_Token_1381 'for' 'crabs'  -> MistakeAction
    * 'at' noun=Noun_Filter_25  -> Examine
    * 'to' / 'toward' / 'towards' noun=Noun_Filter_29  -> A124_facing
    * 'for' scope=Scope_Filter_23  -> A119_finding
    * 'at' scope=Scope_Filter_26  -> A123_local_looking
    * 'at' / 'to' / 'toward' / 'towards' scope=Scope_Filter_30  -> A125_looking_toward
    * 'at' / 'to' / 'toward' / 'towards' scope=Scope_Filter_31  -> A125_looking_toward
    * 'at' noun  -> Examine
    * 'inside' / 'in' / 'into' / 'through' noun  -> Search
    * 'under' noun  -> LookUnder
    * 'behind' noun  -> LookUnder
    * 'through' / 'with' / 'using' held 'at' noun  -> A197_looking_at_it_through reverse
    * 'at' noun 'through' / 'with' / 'using' held  -> A197_looking_at_it_through
    * 'up' topic 'on' / 'in' noun  -> Consult reverse
    * 'up' topic 'in' noun=Noun_Filter_32  -> Consult reverse
    * 'up' topic 'in' noun  -> Consult reverse
    * 'up' topic  -> A147_guidebook_consulting
    * topic 'up' 'in' noun=Noun_Filter_33  -> Consult reverse
    * topic 'up' 'in' noun  -> Consult reverse
    * topic 'up'  -> A147_guidebook_consulting
```

**Comment by angstsmurf** [comment]
This can be solved by adding the line

` Understand "at podium" as the podium.`

That will of course allow all kinds of strange commands, like "put all on at podium", but on the other hand the parser already allows plenty of strange stuff if you abuse it. This might actually be the simplest solution. Can anyone think of any downsides?

**Comment by angstsmurf** [comment]
Unfortunately "wave p-remover at podium" still defaults to the room and not the actual podium. But I think I'm starting to learn how to work around these now.

**Comment by angstsmurf** [comment]
Yes, replacing [something] with [thing] in every relevant grammar line for letter-removing fixes it.

`Understand "use [letter-remover] on [thing]" as waving it at.`

instead of

`Understand "use [letter-remover] on [something]" as waving it at. `

Can anyone think of any downsides to _this_?

**Comment by curiousdannii** [comment]
Relevant: http://inform7.com/mantis/view.php?id=990

I'm still trying to wrap my head around all of this. I've never had to get this detailed into scoping and grammar before.

There wouldn't be any way to just add rooms to the examining action instead of creating a second action, and then just special casing how to carry out examining a room?

**Comment by angstsmurf** [comment]
Yes, that partly explains why [thing] can take precedence over [any locally present room], and [something] can't.

It is apparently possible to do something like this, even if it completely ignores scope:

```
Test Chamber is a room.

A thing called a test is in Test Chamber.

Understand nothing as looking.
Understand nothing as examining.

Understand "x [any object]" or "examine [any object]" as ultra-examining.

Ultra-examining is an action applying to one object.

Carry out ultra-examining:
	if the noun is a room:
		try looking;
	otherwise:
		try examining the noun.

Test me with "examine test / examine test chamber".
```

**Comment by angstsmurf** [comment]
I made a pull request with the added grammar lines with [things]. I kept the old workaround for "look at podium" (looking in the player's command and redirecting local looking) in favor of the simpler but uglier hack of adding "at podium" as a name for the podium.

What do you think? Is there any advantage to implementing a new examine (and a new waving it at) action instead? I guess there would have to be some scope checks in there that would complicate things, as the current location is not usually considered to be in scope.

**Comment by angstsmurf** [comment]
#40 merged. Closing this as resolved.
