### ISSUE TITLE
Reverting fatal errors doesn't work

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#3]
Explanation: http://www.intfiction.org/forum/viewtopic.php?f=19&t=19924&p=108654#p108650

**Comment by curiousdannii** [comment]
Can someone please test this now works?

**Comment by angstsmurf** [comment]
Would anyone object if I posted a link to a gblorb in the forum, asking people to test this?

**Comment by curiousdannii** [comment]
No, that would be fine. Maybe put up a build on dropbox or somewhere?

**Comment by curiousdannii** [comment]
This isn't the fastest way to check the bug has been fixed, but I've added this set of testing instructions to check this bug is fixed (note that you will also have to press space a few times):

```
> test undotest1
> y
> test undotest2
```
