### ISSUE TITLE
Passing secretary test code doesn't always fire.

### ISSUE THREAD

**Issue by akhowell** [i7/counterfeit-monkey#5]
I have completed the game on easy mode, release 5/serial number 140316. At the end of the game, I was still left with the goal of entering the bureau, and was missing the 5 points for passing the secretary test. 
I can verify that when I approached the secretary from the rotunda with contraband items visible, I was correctly stopped.
When I tried to go east with no pass I was correctly stopped.
When I tried to go east without the wig on, I was correctly stopped.
However when I went east with no contraband, both the invitiation and pass, and with the wig on, I was immediately allowed, without the code that should have given me the 5 points getting triggered.
This also occurred if I tried to give the pass or the invitation to the secretary, or if I tried to show the pass or the invitation to the secretary.
The game otherwise played through fine, and no other ill effects were observed even though it should not have been possible to get past that point without earning the 5 points.
In case it matters I was playing using glulxe 0.52/glkterm 1.04 under 64 bit Linux.

**Comment by vlaviano** [comment]
Did you die and answer "yes" to "Shall we suppose we didn't?" prior to going east with no contraband and the code not firing? If so, this is likely a dup of issue #3 caused by 'already caught' remaining true after a resurrection.

**Comment by akhowell** [comment]
Hi,
yes, I believe so.
I logged the issue because I'd emailed Emily and she suggested doing so - I didn't realize there was one already logged, sorry about that, I suspect it is a dupe.
Regards
Aaron

**Comment by vlaviano** [comment]
Closed as duplicate of #3.
