### ISSUE TITLE
Lecture Hall "Programming Error"

### ISSUE THREAD

**Issue by zzxyz** [i7/counterfeit-monkey#50]
I've attached a save file in which the bug can be reproduced by typing "go to podium"
[GoToPodium.zip](https://github.com/i7/counterfeit-monkey/files/355318/GoToPodium.zip)

Lecture Hall (at the podium)
The main lecture hall used for large survey courses in language studies offered to undergraduates. I 
sat through courses here when I was an undergraduate myself, and have now delivered a few 
lectures as a teaching assistant.

A poster at the front of the room announces a conference on cultural reactions to linguistic change. 
It is being held in Nice the day after tomorrow, with Professor Waterstone as keynote speaker, on 
the topic of “homonym shame”. 

The room extends south, full of hard wooden seats. 
[** Programming error: tried to read (something) **]

**Comment by angstsmurf** [comment]
I've noticed that too! Very ugly, even if it seems to be purely cosmetic. It doesn't happen in the current development git version that is built with the 6M62 version of Inform, but it might still be a bug lurking in there somewhere. Thanks for reporting this!

**Comment by angstsmurf** [comment]
I'm closing this for now. It does not happen in any current version of the code, and I can't see any obvious reason why it happened in the old version. It might well be an Inform bug that has been fixed.
