### ISSUE TITLE
Some nitpicks with Startup Precomputation

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#52]
The Startup Precomputation extension is a great addition that removes a lot of the perceived slowness of the game, especially for new players. But sometimes it can trip you up while testing. 

If I compile and run the game in the IDE and forget to delete the "Counterfeit Monkey-startup-data.glkdata" file first, it will hang with "GLK error on startup - glk_image_draw_scaled called with an invalid winid", as it tries to load data for a different version. Would it be in any way possible to check to if the data is made with a different build, and then ignore and overwrite it?

The OS X version of Lectrote stops at startup, complaining about a missing file, until you put an empty Counterfeit Monkey-startup-data.glkdata file in its quixe-files folder. After that it seems to run just fine.

The version of Git with Cheap Glk I've compiled for testing purposes always gives a "Glk library error: stream_open_file: unable to open file" at startup if no startup-data.glkdata file is present.

**Comment by curiousdannii** [comment]
It tests for the existence of the file before trying to open it, and it won't load something for the wrong version. These don't make sense, and if they're happening must be interpreter bugs?

**Comment by angstsmurf** [comment]
Very likely. Probably should be reported to the interpreter authors. Perhaps @erkyrath has an opinion?

I suppose it will be less of a problem in a release version with the startup data in a blorb chunk, as long as the interpreter supports it. It is really only the first one that gives me any trouble, as I for whatever reason keep using the official IDE.

**Comment by curiousdannii** [comment]
>If I compile and run the game in the IDE and forget to delete the "Counterfeit Monkey-startup-data.glkdata" file first, it will hang with "GLK error on startup - glk_image_draw_scaled called with an invalid winid", as it tries to load data for a different version.

This isn't because it's loading a different version of the startup code, but because some of the media/glk extensions we're using aren't GGRecoverObjects aware. At the time when I first implemented it in 0e285377498ed1 I thought that I had all the rules in the correct order. Do you still have this problem at that commit?

**Comment by curiousdannii** [comment]
>It tests for the existence of the file before trying to open it, and it won't load something for the wrong version. These don't make sense, and if they're happening must be interpreter bugs?

Actually I spoke incorrectly - it doesn't check for existence, and just relies on the glk_stream_open_file function to fail if the file doesn't exist. I can make it check for existence first, but I wouldn't have thought it were necessary.

**Comment by angstsmurf** [comment]
> Do you still have this problem at that commit?

I'm not sure what the best way would be to test this, but if I replace the Counterfeit Monkey-startup-data.glkdata with another version and restart, I get a No ident chunk in save file Glk error.

**Comment by curiousdannii** [comment]
If you just do git checkout 0e28537 it will take you to that commit. When you're finished you can git checkout master to go back.

>I get a No ident chunk in save file Glk error.
Okay that should just not be happening! Are you using Zoom? This is all I can see about that error: http://www.intfiction.org/forum/viewtopic.php?f=38&t=7584

**Comment by angstsmurf** [comment]
> If you just do git checkout 0e28537 it will take you to that commit. When you're finished you can git checkout master to go back.

Yeah, sorry. That's what I'm doing. I'm using the official OS X IDE, and there is something in there called ZoomView.framework which I suppose is a variant of Zoom.

**Comment by curiousdannii** [comment]
> The version of Git with Cheap Glk I've compiled for testing purposes always gives a "Glk library error: stream_open_file: unable to open file" at startup if no startup-data.glkdata file is present.

Looking at the cheapglk source code, this is just a warning, but it should still work: https://github.com/erkyrath/cheapglk/blob/cb0d786e12ceba1fbbbf35d0dc990de05d7ad678/cgstream.c#L213
Does the game continue after the warning message? I will change the extension so that it checks for existence first, but it should currently work, just with the warning message.

> Yeah, sorry. That's what I'm doing. I'm using the official OS X IDE, and there is something in there called ZoomView.framework which I suppose is a variant of Zoom.

Zoom has incompatible save files, but I'd expect that it would still not have issues with previous versions of its own save files.

**Comment by angstsmurf** [comment]
Yes, Cheap Glk works as is. It is only a warning message.

**Comment by erkyrath** [comment]
Yes, it's safe to call stream_open_file (reading) when the file doesn't exist.

**Comment by curiousdannii** [comment]
I've made Startup Precomputation safer. Let me know if you still run into any troubles. It won't have fixed the glk_image_draw_scaled error, but I haven't seen it myself so I don't know what's causing it.

**Comment by angstsmurf** [comment]
Good work!

**Comment by angstsmurf** [comment]
I've been experimenting with embedding the precomputation data inside the blorb, but on Lectrote this alway gives me Quixe init: glk_image_draw_scaled: invalid window at startup. Does anyone else have this problem?

**Comment by curiousdannii** [comment]
You can try reordering some of the rules, but really, we'll need to rewrite some extensions to be GGRecoverObjects safe. 

I don't know what would be causing the quixe init error.

**Comment by angstsmurf** [comment]
But you do get it as well, right? I get it on both Mac and Windows Lectrote if I run any Startup Precomputation-enabled build and choose Reset game.

**Comment by curiousdannii** [comment]
I haven't tested it yet sorry.

**Comment by curiousdannii** [comment]
I've updated Simple Graphical Window so this might be fixed now. Can you test it to see if you still get any errors?

**Comment by angstsmurf** [comment]
Nope, seems to work just fine. Excellent!
