### ISSUE TITLE
Map doesn't resize until you move

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#57]
If you change the size of the window the map isn't redrawn at the correct scale until you move.

**Comment by angstsmurf** [comment]
Interesting. I guess Simple Graphical Window is the main suspect.

It seems to work in Lectrote, but the other interpreters I've tested all fail in different ways. Spatterlight handles the map fine, but seems to stop outputting text after resizing. Zoom will enlarge the window correctly, but fails to shrink it. And Gargoyle will behave as you describe, not resizing until after walking, when the game carries out the refresh compass with current directions activity.

**Comment by curiousdannii** [comment]
I think we should move to using Flexible Windows, which will either handle this correctly, or will at least be easier to fix seeing as I know it back to front. We should probably release an update to SGW that uses FW under the hood.

**Comment by angstsmurf** [comment]
Sounds good to me!

**Comment by curiousdannii** [comment]
This is now fixed.
