### ISSUE TITLE
Can't enter car if it is in the garage

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#62]
On my first attempt to produce a car for traveling down High Street, I tried to be very careful: I created the garage first, put the chard into the garage, then transformed it into the card and then the car. To my consternation, however, this meant that I could not get into the car. All phrasings of `get in car`, `enter car`, `drive car` etc. resulted in parser errors or simply going into the garage. When I tried transforming the card directly from my inventory, however, all was well.

**Comment by angstsmurf** [comment]
I think I've fixed this now, as well as #61 . I made a new test build [here](https://dl.dropboxusercontent.com/u/24609432/Counterfeit%20Monkey%20Test.gblorb).

**Comment by angstsmurf** [comment]
Oh, and thanks a lot for reporting these. Even if you don't want to start over with the new build (no save game compatibility between versions, alas) you are welcome to report any other problems with the older version you are playing.

**Comment by SabreCat** [comment]
No problem! I was pleasantly surprised to find an active Git repo for the game, so it's kinda fun to participate!
