### ISSUE TITLE
Routes precomputation?

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#73]
It seems like a no-brainer that the routes in this game should all be precomputed.

In a way we can already do this by running ComputeFWMatrix once at the start of the game and then saving it in the Startup Precomputation file or Blorb chunk, but ideally we want a solution that does not slow down the game start for interpreters that do not support loading Blorb chunks, and more importantly a way to make sure that the routes are never recalculated during the game.

None of this is too complicated in theory, but before I get on with it I'd like to know if anyone else is or has been working on something like this. Perhaps someone has ideas or code to share?

**Comment by curiousdannii** [comment]
Even if the terp can't load the blorb chunk then it's still worth doing because it can use the external file.

I'm not sure if we can always ensure that the routes aren't recalculated, but from my look at it, if we aren't changing the map (or changing whether to use doors or not) then it should be fine.

**Comment by curiousdannii** [comment]
I'd be inclined to say that if it gets called then it needs to actually run. But maybe you could add in a debug logging statement to it and run it through the test suite to see if it does run again?

**Comment by angstsmurf** [comment]
I just can't think of any valid reason why the routes should ever be recalculated in this game. Can you? As long as we block the player approaching the rooms beyond the secret odor-door when it is not open, and perhaps similar rooms that the player is not supposed to know about, there shouldn't be any problem.

**Comment by angstsmurf** [comment]
More or less added as #75 .
