### ISSUE TITLE
Inform 7 6M62 on Ubuntu 16.10 x64 crashes doing Release cborb, Segmentation fault

### ISSUE THREAD

**Issue by BroadcastGames** [i7/counterfeit-monkey#74]
Hello. In the IDE it runs fine, but when I go to make a Release it crashes the Inform 7 IDE every time.  If I do "Release for debug" it works OK - because it does not attempt to bundle the assets with the story.

First off, there is a filename that must be fixed on case-sensitive file systems: `Counterfeit Monkey.materials/Figures/grey-n.png` should be renamed in the repository here on github.

This same system can do Release of other projects fine, even complex ones like Kerkerkruip. Thank you.

**Comment by angstsmurf** [comment]
Sorry to hear that. That file is fixed now, at least.

**Comment by BroadcastGames** [comment]
Thanks for fixing the file. I'm glad counterfeit-monkey was open sourced, it's a good stress test of Inform 7 ;)

**Comment by angstsmurf** [comment]
Does it work now? I seem to be able to make a release on Ubuntu running in VirtualBox now, for what it is worth.

**Comment by BroadcastGames** [comment]
No, the renamed file was essential to get it to do the build - but it crashes after that. Digging deeper, now I see it's actually finishing!  I did a fresh github checkout into an empty directory... and it still bombs the IDE, but it is creating: `Counterfeit Monkey.inform/Build/StatusCblorb.htm` and that HTML file says it finished fine, "All went well", right before it crashes the IDE.

Well, since it is finishing and seems to be purely an IDE issue - I'll close this.  Thanks for fixing the filename.

**Comment by angstsmurf** [comment]
Still, odd that it works for me.

**Comment by BroadcastGames** [comment]
It's crashing somewhere before it renames the file. It's named output.gblorb and it plays fine in interpreters... but it does not do the final file rename.

**Comment by angstsmurf** [comment]
Does the map work properly in the output.gblorb?

Could it have something to do with the space in  the filename? I suppose you might try renaming things, both the actual files and the references in the code.

**Comment by BroadcastGames** [comment]
Yes, the opening map appears. Not sure if it changes with story progression, but it looks like intact.  Wierd. You on 16.10 or 16.04?

**Comment by angstsmurf** [comment]
I was on 16.04, but upgraded to 16.10 now, and I'm afraid it still works just fine here. My Counterfeit Monkey.gblorb is 13 081 464 bytes, so yeah, close enough.
