### ISSUE TITLE
Padding the sides of the map with images?

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#80]
The map still doesn't look great when maximizing the window. 
![skarmavbild 2016-12-30 kl 19 26 01](https://cloud.githubusercontent.com/assets/5066755/21570411/1babaaac-cec6-11e6-95c2-369311f13f89.png)
![skarmavbild 2016-12-30 kl 19 31 02](https://cloud.githubusercontent.com/assets/5066755/21570462/8cf3d5cc-cec6-11e6-86e3-53cf8b808daa.png)
This happens as soon as the graphic window is wider than 722 pixels, the actual width of the map images. I guess one solution would be to have padding images on each side, like the one below but perhaps wider, and crop it as needed. Or it might be simpler and look just as good to pin the map to the left edge of the window and only pad on the right.

![right](https://cloud.githubusercontent.com/assets/5066755/21570591/b7f517f8-cec7-11e6-9d33-836c4b6d401c.png)

**Comment by curiousdannii** [comment]
Yeah my window limits code wasn't finished yet. I'll get to it.

**Comment by angstsmurf** [comment]
Fair enough.
