### ISSUE TITLE
Outdated info text in source header

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#83]
Some of the first text visible in the source when opening the Counterfeit Monkey project reads as follows:

>This source is provided for its interest value. Not all of the extensions necessary to compile the source are available to the public and it is not the author's intention to have others recompile or revise the game.

The bit about extensions not being available seems incorrect, as I am able to play and release the source from this repository without issue. The bit about "it is not the author's intention" is also, I should hope, incorrect: the maintainers of this repo appear to still be in touch with Emily and have her permission to open-source her text. Should this section be removed?

**Comment by emshortif** [comment]
Sure, feel free to remove that section. The intent was to prevent people from spamming me with help compiling it when I was the sole maintainer.

**Comment by angstsmurf** [comment]
I removed that paragraph in a609326.
