### ISSUE TITLE
Waterstone should react to being shown his draft

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#84]
At last, I have reached the scene with Professor Waterstone, for real!

I obtained his draft speech from the printer. I tried to show it to him.

> He seems to get that we're trying to show him the draft document, but as it is not related to the concept of homonym shame, it's not much help with his paper, so he probably doesn't want to be distracted.

Given it _is_ his paper, and thus _very much_ related to homonym shame, this result is a little incongruous. XD Supposing that obtaining the draft document is more of a puzzle hint than an item you'll need later (I get a first-letter razor as hinted at in one of the memories, and need a "raft document"?), I'd suggest instead a little scene where Waterstone takes his document, with a curt thanks for running gofer.

**Comment by angstsmurf** [comment]
Good idea!

However, it would probably reduce the impact of the final solution if Waterstone actually came up to the door and opened it at that stage.

At first I considered having him ask us to just leave it in his mailbox, but we really want to avoid drawing the player's attention to unimportant scenery like that. Instead I've added what amounts to a couple of clues, see 5985656. Any suggestions or improvements are welcome.

**Comment by SabreCat** [comment]
Nice! That approach fits the rest of the scene well.
