### ISSUE TITLE
Don't award secretary score until "Have a nice day"

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#86]
When undergoing the gauntlet of secretarial inspection in the Bureau of Orthography, you get a score notification right in the middle of the dialogue:

>"He sent me to do some research in his place. I'm a student of his."
> 
> She frowns. "Invitations to inspect highly secure machinery are not transferrable," she says. "And how should I know whether you stole it?"
> 
> [Your score has gone up by five points and is now seventy-eight.]

Inspecting `score` informs you that you have "[passed] the secretarial test". For the sake of the scene's tension, it might make more sense to award the points only at the very end of the sequence--the secretary's "have a nice day!" That way, the player can still sweat with the protagonists for a bit, unsure of whether or not they've done everything necessary to pass the checkpoint, until it's truly over.

**Comment by angstsmurf** [comment]
That seems like an obvious improvement. Implemented in 0eca54f.

Speaking of the scene's tension, I quite miss [this bit](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Tools.i7x#L1090) from the early versions of the game. I wonder if there is a good place somewhere to sneak it back in.
