### ISSUE TITLE
Guards can come seize you even after you've escaped (?)

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#87]
I finished the game first without installing a new Atlantida. On that route, when I climbed down from the window to the beach, there was a message to the effect that whoever might be pursuing me wouldn't be able to catch me after that point.

After that, I hit up a walkthrough (it would have been a lot more stumbling around before I ever thought to simply homonym the atlantida back) to try for a better ending. However, it seems impossible to actually escape and finish the game, on this path. Even wasting as little time as possible--ignoring all conversation prompts, `undo`ing if I so much as do an extra `look` or bobble a directional move--the guards arrive and capture me either the instant I exit the private solarium through the window, or once I descend to the beach.

1) On the previous route, it seemed like I was safe from the guards as soon as I got out the window. Why are they able to pursue me outside on this route?

2) ~Even with the above fixed, the timer could stand a to be at least a few turns more lenient. That way the player can actually converse with one or both of the Atlantidas, as opposed to shortcutting through the climax as efficiently as possible.~ Turns out I was missing a step to give myself more time; ignore this bit!

**Comment by angstsmurf** [comment]
That's annoying. I tried to fix this problem not long ago, but apparently unsuccessfully. There is a message to the effect that Atlantida closes and locks the window behind you, so you should actually get more time, not less, when she is restored. I'll look into it.

Do you remember if you did remove the jack from the portcullis after going through it while being chased by the guards?

**Comment by SabreCat** [comment]
Oho, I did not! I'll give that a shot, see if that's sufficient to get me through to the conclusion.

**Comment by SabreCat** [comment]
Studying the source code postgame, I think the trouble is here:

https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Animal%20Actions%20and%20Human%20Conversation.i7x#L6188

`Portcullis-threat` does not have an "ends in freedom" condition regarding the Precarious Perch, the way most of the other countdowns do. If it's intended that removing the jack is the _only_ solution to the refreshed Atlantida escape, the timer should be reduced by a couple of turns so the player can never make it out the window without forcing a delay. If speedy feet are meant to be a solution as well as dropping the portcullis, we need a similar escape clause on portcullis-threat.

**Comment by angstsmurf** [comment]
You are right, of course. It seems likely that the original intention is that the only solution is to close the portcullis again, so I've committed a minimal fix for this that ends the scene in capture as soon as we enter the solarium, along with some safeguards in case there is still some bug lingering that allows the player to bypass this. Ideally there should at least be some clue that the player is supposed to delay the guards.

**Comment by SabreCat** [comment]
This works, but yeah, it's then important to communicate that entering the solarium is a fail state. Maybe a message to the effect that you can hear guards coming down into the Tunnel through Chalk, and if you don't find a way to delay them, they'll be upon you in a moment? Of course, then _returning to the Tunnel_ would also need to be a fail state, trapping the player in the Personal Apartment until they figure out the solution.

**Comment by angstsmurf** [comment]
Right. I took another stab at this with 5d13025. Now we disallow going east from Personal Apartment until we have closed the portcullis.

**Comment by angstsmurf** [comment]
FYI There are a couple of well-hidden test commands for trying out this part of the game in a debug build. Just type > ESTABLISH followed by > TEST ORACLE
