### ISSUE TITLE
GO TO (location) does not fulfill relevant tutorial step

### ISSUE THREAD

**Issue by SabreCat** [i7/counterfeit-monkey#88]
If you keep the tutorial on and play along, the prompts will inform you that it is possible to GO TO a specific location rather than heading there one step at a time. It suggests GO TO BACK ALLEY. However, if you obligingly perform that action, the tutorial continues to bug you about GO TO BACK ALLEY as if you hadn't.

I need to do a bit of testing to confirm, but possibly the warping-around pathfinding introduced in #75 bypasses the condition that would fulfill the tutorial step?

**Comment by SabreCat** [comment]
Confirmed that at least the bug was introduced in #75 or later. Resetting the repo to deba7f5, compiling, and playing the tutorial, GO TO BACK ALLEY moves us on to another step.

**Comment by angstsmurf** [comment]
Thanks! This should be fixed now.

I added some code in #75 that converted GO TO ROOM into a singe GO (direction) if the destination was only one room away, which of broke this part of the tutorial.
