### ISSUE TITLE
Can't leave snap in Samuel John Basement

### ISSUE THREAD

**Issue by KeyboardSounds** [i7/counterfeit-monkey#89]
Interpreter: Windows Gluxle 0.5.3.146
You can't enter the Rectification Room without leaving a sound making object in the hallway, but if you drop the snap in the hallway and then enter the Room, you automatically pick up the snap and can't enter the room.

The ring works, though.

**Comment by angstsmurf** [comment]
In the current Github version, there is a message explaining that we don't want to leave the snap behind. Perhaps the message could be clearer. Or perhaps we should just allow leaving the snap there until the player goes up from the basement.

**Comment by angstsmurf** [comment]
I guess this is resolved.

**Comment by angstsmurf** [comment]
I just changed this behavior so that the snap now can be temporarily left in the basement until we leave.
