### ISSUE TITLE
Problem with Synthesizer

### ISSUE THREAD

**Issue by FrumpyJones** [i7/counterfeit-monkey#95]
I'm playing the game at iplayif.

This is either a bug or I am really really missing something.

I am looking at the synthesizer.  It says There is a Pass and a Key in it.  But regardless of the order I put them in (I have tried doing it so I see a Key and a Pass), when I turn on the synthesizer it just states:

"The synthesizer whirs for a moment, then dies down again"

I tried putting them on, in and into...

So, bug?  or am I dim?

**Comment by angstsmurf** [comment]
A passkey is probably something that should be implemented, but if you are stuck where I think you are, you should consider SPOILER WARNING experimenting with a card instead.

**Comment by angstsmurf** [comment]
… or try using the pass on its own, as a matter of fact.

**Comment by FrumpyJones** [comment]
Yeah.... I was dim...

**Comment by angstsmurf** [comment]
I'll close this now, though we probably should at least implement a response to trying to create a passkey.
