### ISSUE TITLE
Publish release 7

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#96]
If you're satisfied with where the code is, then you should go ahead and publish it!

If it helps, the Kerkerkruip project has a [list of tasks to do when releasing](https://github.com/i7/kerkerkruip/wiki/Release-protocol). A lot of it wouldn't apply to this of course, but it might remind you of something you'd otherwise forget.

**Comment by angstsmurf** [comment]
Thanks!

I guess the main blocker is getting a go-ahead from @emshortif for any non-trivial changes to puzzle design and output text. I sent her an e-mail some time ago with a list of changes, and she basically replied that she'd get back to me.

**Comment by emshortif** [comment]
Okay — I’m in Argentina for a conference at the moment but if this is becoming a blocker I’ll try to get to it when I get back (early next week) if that’s okay?

**Comment by angstsmurf** [comment]
There's no rush! And of course I'll revert anything you're not happy about. Just let me know.

**Comment by curiousdannii** [comment]
One additional thing which the testing version you've been sharing on dropbox won't have (I assume) is the startup snapshot.

**Comment by angstsmurf** [comment]
Oh yes, I forgot about that. I disabled that locally. I think it was when I was experimenting with running the game on my phone. I know you worked hard on that code, but now that we have eliminated most start-up initialisation anyway, I'm not sure how much difference it makes any more. Do you think we should keep it enabled?

**Comment by curiousdannii** [comment]
It's a little bit of extra work before publishing which may make it bearable for the slowest of computers/phones (and has no down sides for faster computers) so I'd say we should still do it.

**Comment by angstsmurf** [comment]
Of course. Sorry about that! I've replaced the [test version in my Dropbox ](https://www.dropbox.com/s/n8nfrkr45yb0zqp/Counterfeit%20Monkey%20Test.gblorb?dl=0) with a new build using only committed code.

**Comment by angstsmurf** [comment]
I think it is ready for release now. 

https://www.dropbox.com/s/qh7g5unj7ngxzhs/Counterfeit%20Monkey.gblorb?dl=0

Are you okay with hiding the Startup Precomputation message ("Counterfeit Monkey is starting. This may take a short moment.")?

**Comment by curiousdannii** [comment]
If you don't think it helps, because of all the other speed improvements, then definitely, go ahead and remove it :)

**Comment by angstsmurf** [comment]
Thanks for your understanding! I have this idea that any changes we make should be as invisible as possible, so that we try to avoid any output text that isn't written by Emily. I'm sure you can find places where I haven't followed this myself, though.

**Comment by angstsmurf** [comment]
I'll try to make a release here on Github. Needless to say, you're welcome to make changes or additions.

**Comment by curiousdannii** [comment]
Well done!
