### ISSUE TITLE
Non-interactive profiling mode

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#97]
I would love a mode where we can compile the game to non-interactively run a full game script and then at the end print out the time it took.

This might be able to be patched on to the other test stuff, or it could probably be self-contained.

I'll get to this eventually myself, but if anyone else wants to do it for me I'd be very appreciative :)

**Comment by angstsmurf** [comment]
test.sh in tools does this. Or do you mean that it should all be done in the game code? What is the use case?

I've looked at glk_request_timer_events, but I'm not sure how to measure total play time. Is there any example code anywhere?

**Comment by curiousdannii** [comment]
Yeah I meant all in the game code. It would start and try to load a hardcoded transcript file, and if it can't then it would continue normally.

`glk_current_time` gives you the current time, so if you call it at the beginning and end you can get the run time.

Use case is for very simply testing and comparing interpreters. Cross platform, mobile apps etc. test.sh is great! But for less flexibility it could be even simpler.

**Comment by angstsmurf** [comment]
I'll give it a try.

**Comment by curiousdannii** [comment]
Don't worry if you can't, as I said, I'll get to it myself eventually!

**Comment by angstsmurf** [comment]
I think we can consider this implemented in #98.
