### ISSUE TITLE
Item is lost if transformed while being weared

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#99]
Mourning dress annihilates when transformed while being worn. I don't know whether this behavior applies to all wearable objects, because I am not that far into game yet.

Exact steps are:
[obtain gel]
1> go to sigil street
2> remove u from dress
3> use gel on dress
4> take dress
5> put on dress
6> remove u from dress

Alexandra takes the dress off, transforms it into "morning dress", and then it's gone — it's not in inventory, and it's not on the ground. I think this is a bug, because if you take it off first, it transforms without any issue, and can be worn afterwards.

This reproduces on Release 6.

**Comment by angstsmurf** [comment]
I think that the dress is supposed to be behind glass and not meant to fall out when transformed. This should be fixed by  7b374e1.
